// Newly written learner adaptations of traditional tales, not modern editions.
export const childrenStories = [
 {
  id:'children-perez',kind:'Stories',track:'Beginner',title:'El Ratoncito Pérez',englishTitle:'Pérez the little mouse',focus:'Children’s tale · Spain · Possession and location',
  intro:'An original little adventure inspired by the tooth-mouse tradition associated with Spain. This is not a retelling of every event in Luis Coloma’s story. Find what goes under the pillow.',
  source:['Tradition: Instituto Cervantes','https://cvc.cervantes.es/actcult/raton/protagonistas03.htm'],
  lines:[
   ['A Lucía se le cae un diente pequeño.','Lucía loses a little tooth.'],
   ['—¡Mamá, mira mi diente! —dice con una sonrisa.','“Mom, look at my tooth!” she says with a smile.'],
   ['Su madre le habla del Ratoncito Pérez.','Her mother tells her about Pérez the little mouse.'],
   ['—Pon el diente debajo de la almohada —le dice.','“Put the tooth under the pillow,” she tells her.'],
   ['Lucía prepara también una nota: «Gracias por venir».','Lucía also prepares a note: “Thank you for coming.”'],
   ['Por la noche, un ratón con una bolsa entra en la habitación.','At night, a mouse with a bag enters the bedroom.'],
   ['El diente está debajo de una almohada enorme.','The tooth is under an enormous pillow.'],
   ['Pérez empuja la almohada, pero pesa demasiado.','Pérez pushes the pillow, but it is too heavy.'],
   ['Entonces Lucía se mueve mientras duerme.','Then Lucía moves in her sleep.'],
   ['Ahora el ratón puede recoger el diente.','Now the mouse can pick up the tooth.'],
   ['En su lugar deja una moneda y guarda la nota en su bolsa.','In its place he leaves a coin and puts the note in his bag.'],
   ['Por la mañana, Lucía encuentra la moneda.','In the morning, Lucía finds the coin.'],
   ['—¡Pérez sabe leer! —dice al ver que ya no está la nota.','“Pérez knows how to read!” she says when she sees that the note is gone.']
  ],
  vocab:[['el diente','the tooth'],['la almohada','the pillow'],['la moneda','the coin'],['recoger','to pick up']],
  tip:'Follow the locations: debajo de la almohada, en su lugar, en su bolsa.',
  proTip:'Ratoncito is a diminutive of ratón. The ending can suggest small size or affection. Ratón has an accent; ratoncito does not.',
  taglish:'Se le cae un diente means a tooth falls out. Sa story, present tense ang main actions: entra, deja, encuentra. Sabe leer means knows how to read.',
  questions:[['What does Lucía put under her pillow?',['A coin','A tooth','A bag'],1,'Her mother tells her to put the tooth debajo de la almohada.'],['What makes it possible to reach the tooth?',['Lucía moves in her sleep','Her mother lifts the bed','The pillow disappears'],0,'Lucía se mueve mientras duerme; then Pérez can pick up the tooth.'],['Why does Lucía think Pérez can read?',['He reads aloud','He brings a book','Her note is gone'],2,'Her conclusion comes from noticing that the note is no longer there.']]
 },
 {
  id:'children-pigs',kind:'Stories',track:'Beginner',title:'Los tres cerditos',englishTitle:'The three little pigs',focus:'Children’s classic · Materials and repeated actions',
  intro:'A simplified retelling of the traditional tale, with a gentle ending. This is a shared children’s classic, not a story that originated in Mexico or Spain. Compare the three houses.',
  source:['Classic tales: Instituto Cervantes','https://libroselectronicos.cervantes.es/resources/60ed802ca78cb70001f71c07'],
  lines:[
   ['Tres cerditos quieren construir sus propias casas.','Three little pigs want to build their own houses.'],
   ['El primero hace una casa de paja porque quiere terminar pronto.','The first builds a straw house because he wants to finish soon.'],
   ['El segundo hace una casa de madera y después sale a jugar.','The second builds a wooden house and then goes out to play.'],
   ['El tercero trabaja más tiempo y construye una casa de ladrillos.','The third works longer and builds a brick house.'],
   ['Un lobo llega a la casa de paja y llama a la puerta.','A wolf arrives at the straw house and knocks on the door.'],
   ['El cerdito no abre, así que el lobo sopla muy fuerte.','The little pig does not open it, so the wolf blows very hard.'],
   ['La casa cae y el cerdito corre a la casa de madera.','The house falls down and the little pig runs to the wooden house.'],
   ['El lobo los sigue y vuelve a soplar.','The wolf follows them and blows again.'],
   ['La madera tampoco resiste, y los dos corren a la tercera casa.','The wood does not hold up either, and the two run to the third house.'],
   ['Su hermano abre la puerta y los deja entrar.','Their brother opens the door and lets them in.'],
   ['El lobo sopla una vez, dos veces, tres veces.','The wolf blows once, twice, three times.'],
   ['La casa de ladrillos no se mueve.','The brick house does not move.'],
   ['Cansado, el lobo se marcha por el camino.','Tired, the wolf leaves along the path.'],
   ['Los tres hermanos preparan la cena y hacen planes para construir juntos.','The three brothers prepare dinner and make plans to build together.']
  ],
  vocab:[['la paja','straw'],['la madera','wood'],['el ladrillo','the brick'],['soplar','to blow']],
  tip:'De names the material: de paja, de madera, de ladrillos.',
  proTip:'Vuelve a soplar means blows again. Volver a + infinitive expresses repetition, not necessarily a physical return.',
  taglish:'Primero, segundo, tercero identify the order. Los sigue = follows them; los refers to the pigs. Tampoco means not either, kaya bumagsak din ang second house.',
  questions:[['Why does the first pig use straw?',['He wants to finish quickly','He cannot find his brothers','The wolf asks him to'],0,'The story says porque quiere terminar pronto.'],['Which house stays standing?',['The straw house','The wooden house','The brick house'],2,'La casa de ladrillos no se mueve.'],['What do the brothers plan at the end?',['To follow the wolf','To build together','To move into the forest'],1,'They make plans para construir juntos.']]
 },
 {
  id:'children-hare',kind:'Stories',track:'Beginner',title:'La liebre y la tortuga',englishTitle:'The hare and the tortoise',focus:'Traditional fable · Comparisons and steady effort',
  intro:'A simplified version of the fable traditionally attributed to Aesop, shared in many languages. Read for the difference between being fast and finishing a task.',
  source:['Fable: Biblioteca Virtual Miguel de Cervantes','https://www.cervantesvirtual.com/portales/biblioteca_literatura_infantil_juvenil/222464_libre_y_tortuga/'],
  lines:[
   ['Una liebre se ríe de una tortuga que camina despacio.','A hare laughs at a tortoise that walks slowly.'],
   ['—Soy mucho más rápida que tú —dice la liebre.','“I am much faster than you,” says the hare.'],
   ['—Es verdad, pero puedo llegar lejos —responde la tortuga.','“That is true, but I can go far,” replies the tortoise.'],
   ['Las dos deciden hacer una carrera hasta un árbol.','The two decide to race to a tree.'],
   ['Un zorro señala la salida y da la señal.','A fox points to the starting line and gives the signal.'],
   ['La liebre corre y pronto deja atrás a la tortuga.','The hare runs and soon leaves the tortoise behind.'],
   ['Como tiene mucha ventaja, se acuesta a descansar.','Since she has a big lead, she lies down to rest.'],
   ['Cierra los ojos y se queda dormida.','She closes her eyes and falls asleep.'],
   ['La tortuga sigue caminando sin detenerse.','The tortoise keeps walking without stopping.'],
   ['Pasa junto a la liebre y continúa hacia el árbol.','She passes beside the hare and continues toward the tree.'],
   ['Cuando la liebre despierta, la tortuga está cerca de la meta.','When the hare wakes up, the tortoise is near the finish line.'],
   ['La liebre corre tan rápido como puede, pero llega después.','The hare runs as fast as she can, but arrives afterward.'],
   ['La tortuga gana y la liebre deja de burlarse de ella.','The tortoise wins and the hare stops making fun of her.']
  ],
  vocab:[['la liebre','the hare'],['la carrera','the race'],['la ventaja','the lead / advantage'],['la meta','the finish line / goal']],
  tip:'Más rápida que compares speed. Sigue caminando tells you the tortoise continues walking.',
  proTip:'Como at the beginning of Como tiene mucha ventaja introduces a reason: since or because. It does not mean I eat in this sentence.',
  taglish:'La liebre and la tortuga are feminine nouns, kaya rápida at dormida ang agreement. The lesson is about effort and overconfidence; hindi sinasabi na laging mas mabilis ang slow animals.',
  questions:[['Why does the hare stop?',['She is injured','She has a big lead','She cannot see the tree'],1,'Como tiene mucha ventaja explains her decision to rest.'],['What does the tortoise do while the hare sleeps?',['Keeps walking','Goes home','Wakes the fox'],0,'Sigue caminando sin detenerse states her continued action.'],['Which lesson fits the outcome?',['Speed never helps','Sleeping always wins races','Steady effort can overcome overconfidence'],2,'The tortoise continues; the faster hare loses after assuming she has plenty of time.']]
 },
 {
  id:'children-goldilocks',kind:'Stories',track:'Beginner',title:'Ricitos de Oro y los tres osos',englishTitle:'Goldilocks and the three bears',focus:'Children’s classic · Size, temperature, and contrast',
  intro:'A simplified traditional tale with an added apology at the end. Notice repeated descriptions: grande, pequeño, caliente, frío. This shared classic has roots outside Mexico and Spain.',
  lines:[
   ['Tres osos viven en una casa en el bosque.','Three bears live in a house in the forest.'],
   ['Una mañana salen a pasear mientras se enfría su comida.','One morning they go for a walk while their food cools.'],
   ['Una niña llamada Ricitos de Oro encuentra la casa.','A girl called Goldilocks finds the house.'],
   ['Llama a la puerta, pero nadie responde.','She knocks at the door, but nobody answers.'],
   ['Entra sin permiso y ve tres platos de sopa.','She enters without permission and sees three bowls of soup.'],
   ['La primera sopa está demasiado caliente y la segunda está demasiado fría.','The first soup is too hot and the second is too cold.'],
   ['La tercera está perfecta, y la niña se la come.','The third is just right, and the girl eats it.'],
   ['Después prueba una silla grande, una mediana y una pequeña.','Then she tries a large chair, a medium one, and a small one.'],
   ['La silla pequeña se rompe cuando se sienta.','The small chair breaks when she sits down.'],
   ['En el dormitorio encuentra tres camas y se duerme en la más pequeña.','In the bedroom she finds three beds and falls asleep in the smallest.'],
   ['Los osos vuelven y descubren la sopa, la silla rota y a la niña.','The bears return and discover the soup, the broken chair, and the girl.'],
   ['Ricitos de Oro despierta y se asusta al verlos.','Goldilocks wakes up and gets frightened when she sees them.'],
   ['—Perdón. No debía entrar sin permiso —dice antes de salir.','“Sorry. I should not have entered without permission,” she says before leaving.'],
   ['Más tarde vuelve con su familia para ayudar a reparar la silla.','Later she returns with her family to help repair the chair.']
  ],
  vocab:[['el bosque','the forest'],['demasiado','too / too much'],['mediano / mediana','medium-sized'],['sin permiso','without permission']],
  tip:'Look at the repeated sets of three. They help you predict and remember vocabulary.',
  proTip:'Demasiado stays unchanged when it modifies an adjective: demasiado caliente, demasiado fría. With a noun it can agree: demasiada sopa.',
  taglish:'Se enfría = cools down; se rompe = breaks. La más pequeña means the smallest one, referring to cama. The apology is an added gentle ending for this adaptation.',
  questions:[['Why do the bears go for a walk?',['To find the girl','To buy a chair','To let their food cool'],2,'They go out mientras se enfría su comida.'],['What breaks?',['The small chair','The large bed','The front door'],0,'La silla pequeña se rompe.'],['Why does the girl return with her family?',['To eat more soup','To help repair the chair','To race the bears'],1,'The last line says para ayudar a reparar la silla.']]
 },
 {
  id:'children-moon-rabbit',kind:'Stories',track:'Intermediate',title:'El conejo en la luna',englishTitle:'The rabbit in the moon',focus:'Mexican legend · Generosity and past narration',
  intro:'A simplified, gentle adaptation of a Mexican legend associated with Mexica tradition. There are different tellings. This version softens the rabbit’s offer and focuses on sharing; it is a legend, not a scientific explanation of the Moon.',
  source:['Cultural context: Secretaría de Educación Pública','https://nuevaescuelamexicana.sep.gob.mx/contenido/coleccion/la-leyenda-como-tradicion-oral/'],
  lines:[
   ['Cuenta una leyenda que Quetzalcóatl recorrió la tierra con aspecto humano.','A legend tells that Quetzalcóatl traveled the earth in human form.'],
   ['Caminó durante horas, hasta que el cielo se llenó de estrellas.','He walked for hours, until the sky filled with stars.'],
   ['Estaba cansado y tenía hambre, así que se sentó junto al camino.','He was tired and hungry, so he sat beside the path.'],
   ['Un conejo se acercó y le preguntó qué le pasaba.','A rabbit approached and asked him what was wrong.'],
   ['—He caminado mucho y no tengo nada que comer —respondió el viajero.','“I have walked a long way and have nothing to eat,” the traveler replied.'],
   ['El conejo le ofreció la hierba que había recogido.','The rabbit offered him the grass it had gathered.'],
   ['El viajero agradeció el gesto, pero explicó que no podía comer hierba.','The traveler appreciated the gesture, but explained that he could not eat grass.'],
   ['—Tengo muy poco, pero quiero compartirlo contigo —dijo el conejo.','“I have very little, but I want to share it with you,” said the rabbit.'],
   ['Quetzalcóatl vio que aquel pequeño animal tenía un corazón generoso.','Quetzalcóatl saw that the little animal had a generous heart.'],
   ['Lo levantó suavemente hacia la luna brillante.','He gently lifted it toward the bright moon.'],
   ['Allí quedó marcada la figura del conejo.','The rabbit’s shape remained marked there.'],
   ['Después lo dejó de nuevo en la tierra, sano y salvo.','Then he placed it back on earth, safe and sound.'],
   ['Según esta leyenda, su figura recuerda que incluso los más pequeños tienen algo que ofrecer.','According to this legend, its shape reminds us that even the smallest have something to offer.']
  ],
  vocab:[['con aspecto humano','in human form'],['la hierba','grass'],['compartir','to share'],['sano y salvo','safe and sound']],
  tip:'Estaba and tenía describe the traveler’s condition. Caminó and se sentó tell the main events.',
  proTip:'Había recogido places the gathering before the offer. Según esta leyenda marks the explanation as part of a traditional narrative.',
  taglish:'Lo levantó: lo refers to the conejo. Le ofreció: le points to the traveler receiving the offer. Magkaiba ang direct object at recipient.',
  questions:[['What does the rabbit first offer?',['A coin','Grass','A bowl of soup'],1,'Le ofreció la hierba que había recogido.'],['Why does Quetzalcóatl honor the rabbit?',['It runs fastest','It knows the way home','It wants to share what little it has'],2,'The rabbit’s wish to share reveals its generosity.'],['What does the last sentence explain?',['The meaning of the rabbit’s image within the legend','How astronauts reached the Moon','Why grass grows at night'],0,'Según esta leyenda frames the image as a traditional reminder of generosity.']]
 },
 {
  id:'children-tlacuache',kind:'Stories',track:'Intermediate',title:'El tlacuache y el fuego',englishTitle:'The opossum and the fire',focus:'Mexican legend · A small animal helps a community',
  intro:'A gentle, simplified retelling of a fire-bringing legend told in different Indigenous traditions in Mexico. Characters and events vary by community. This version leaves out violent episodes and treats the tail’s appearance as a story explanation.',
  source:['Cultural context: Instituto Nacional de los Pueblos Indígenas','https://www.gob.mx/inpi/articulos/el-tlacuache-y-el-fuego-una-historia-que-ha-acompanado-infinidad-de-noches-frente-al-fogon-libro-electronico?idiom=es'],
  lines:[
   ['Hace mucho tiempo, cuenta la leyenda, una comunidad vivía sin fuego.','Long ago, the legend says, a community lived without fire.'],
   ['Por las noches hacía frío y la gente no podía calentarse.','At night it was cold and the people could not warm themselves.'],
   ['El fuego estaba lejos, en un lugar donde lo vigilaba un guardián.','The fire was far away, in a place where a guardian watched over it.'],
   ['Varios animales querían ayudar, pero no sabían cómo acercarse.','Several animals wanted to help, but did not know how to approach.'],
   ['Entonces un tlacuache pequeño se ofreció a intentarlo.','Then a little opossum offered to try.'],
   ['—No soy el más grande, pero puedo buscar una oportunidad —dijo.','“I am not the biggest, but I can look for an opportunity,” it said.'],
   ['Llegó despacio y pidió permiso para descansar cerca del calor.','It arrived slowly and asked permission to rest near the warmth.'],
   ['El guardián lo dejó quedarse porque parecía inofensivo.','The guardian let it stay because it seemed harmless.'],
   ['Cuando nadie lo miraba, el tlacuache tomó una brasa con la cola.','When nobody was watching it, the opossum took an ember with its tail.'],
   ['Corrió de vuelta para llevar el fuego a la comunidad.','It ran back to bring the fire to the community.'],
   ['La brasa le quemó el pelo de la cola, pero logró llegar.','The ember burned the hair on its tail, but it managed to arrive.'],
   ['La gente recibió el fuego y cuidó al pequeño animal.','The people received the fire and cared for the little animal.'],
   ['Desde entonces, dice el relato, el tlacuache lleva la cola sin pelo como recuerdo de su ayuda.','Since then, the story says, the opossum has had a hairless tail as a reminder of its help.']
  ],
  vocab:[['el tlacuache','the opossum'],['el guardián','the guardian'],['la brasa','the ember'],['la cola','the tail']],
  tip:'Find the problem, the plan, and the result. Retell each in one short sentence.',
  proTip:'Logró llegar means managed to arrive. Lograr + infinitive presents a successfully achieved action.',
  taglish:'Hacía frío describes background weather. Tomó and corrió move the story forward. Tlacuache is a Mexican word for an opossum; zarigüeya is another Spanish name.',
  questions:[['What does the community lack?',['Water','Food','Fire'],2,'The opening says the community vivía sin fuego.'],['Why does the guardian let the animal stay?',['It seems harmless','It brings a gift','It is the biggest animal'],0,'Porque parecía inofensivo gives the reason.'],['What feature does the legend explain?',['Its large ears','Its hairless tail','Its sleeping place'],1,'The final sentence links its cola sin pelo to carrying the ember.']]
 },
 {
  id:'children-maize',kind:'Stories',track:'Intermediate',title:'El maíz y la hormiga',englishTitle:'The maize and the ant',focus:'Mexican legend · Asking for help and transformation',
  intro:'A short adaptation of the traditional story of Quetzalcóatl and the ant that leads him to maize. This retelling condenses the journey and ending. Read for how a small helper solves a large problem.',
  source:['Traditional motif: CONABIO','https://www.biodiversidad.gob.mx/publicaciones/versiones_digitales/Bichos.pdf'],
  lines:[
   ['Cuenta una leyenda que la gente buscaba un alimento que pudiera cultivar.','A legend tells that people were looking for a food they could grow.'],
   ['Quetzalcóatl quería ayudar, pero no sabía dónde encontrar el maíz.','Quetzalcóatl wanted to help, but did not know where to find maize.'],
   ['Un día vio una hormiga que llevaba un grano entre las mandíbulas.','One day he saw an ant carrying a grain between its jaws.'],
   ['—¿De dónde viene ese grano? —le preguntó.','“Where does that grain come from?” he asked it.'],
   ['La hormiga siguió su camino y él caminó a su lado.','The ant continued on its way and he walked beside it.'],
   ['Finalmente, ella aceptó mostrarle el lugar.','Finally, it agreed to show him the place.'],
   ['La entrada era tan estrecha que Quetzalcóatl no podía pasar.','The entrance was so narrow that Quetzalcóatl could not get through.'],
   ['Entonces se convirtió en una hormiga para seguir a su guía.','Then he turned into an ant to follow his guide.'],
   ['Juntos recorrieron un paso oscuro hasta llegar a los granos de maíz.','Together they traveled through a dark passage until they reached the maize grains.'],
   ['Quetzalcóatl tomó un grano y lo llevó de vuelta.','Quetzalcóatl took a grain and carried it back.'],
   ['Al regresar, recuperó su forma y entregó el maíz a la gente.','Upon returning, he regained his form and gave the maize to the people.'],
   ['La comunidad aprendió a sembrarlo y a cuidar las plantas.','The community learned to sow it and care for the plants.'],
   ['En esta historia, la ayuda de una hormiga abre un camino que la fuerza sola no podía abrir.','In this story, an ant’s help opens a path that strength alone could not open.']
  ],
  vocab:[['el maíz','maize / corn'],['la hormiga','the ant'],['el grano','the grain'],['sembrar','to sow / plant seeds']],
  tip:'Se convirtió en tells you what someone turned into. Look for the reason for the transformation.',
  proTip:'Un alimento que pudiera cultivar describes the kind of food being sought, rather than a specific food already identified. Pudiera is imperfect subjunctive.',
  taglish:'Lo llevó: lo refers to un grano. Sembrarlo joins sembrar + lo, referring to maize. Maíz means corn; hindi pareho ang whole plant, grain, at prepared food.',
  questions:[['Who knows where the maize is?',['The ant','The community','A rabbit'],0,'The ant is carrying a grain and eventually shows the place.'],['Why does Quetzalcóatl become an ant?',['To hide from the people','To fit through the narrow entrance','To win a race'],1,'The entrance is too narrow for him before the transformation.'],['What does the community learn?',['To build a brick house','To carry fire','To sow maize and care for the plants'],2,'Aprendió a sembrarlo y a cuidar las plantas states the result.']]
 },
 {
  id:'children-red-riding',kind:'Stories',track:'Intermediate',title:'Caperucita Roja',englishTitle:'Little Red Riding Hood',focus:'Children’s classic · Dialogue and past events',
  intro:'A gentle adaptation of the European folk tale shared in Spanish-language children’s collections. In this version, nobody is eaten: the grandmother hides and a neighbor helps. Follow the clues that reveal the wolf.',
  source:['Classic tale: Biblioteca Virtual Miguel de Cervantes','https://www.cervantesvirtual.com/obra-visor/caperucita-roja--0/html/004a3704-82b2-11df-acc7-002185ce6064_2.html'],
  lines:[
   ['Había una vez una niña que llevaba una caperuza roja.','Once upon a time there was a girl who wore a little red hood.'],
   ['Un día, su madre le dio una cesta para su abuela.','One day, her mother gave her a basket for her grandmother.'],
   ['—Sigue el camino y no te detengas —le dijo.','“Follow the path and do not stop,” she told her.'],
   ['En el bosque, un lobo le preguntó adónde iba.','In the forest, a wolf asked her where she was going.'],
   ['Caperucita le contó que visitaba a su abuela al otro lado del bosque.','Little Red Riding Hood told him that she was visiting her grandmother on the other side of the forest.'],
   ['El lobo tomó un atajo mientras ella se detenía a recoger flores.','The wolf took a shortcut while she stopped to pick flowers.'],
   ['Al verlo llegar, la abuela se escondió en un armario.','When she saw him arrive, the grandmother hid in a wardrobe.'],
   ['El lobo se puso un gorro y se metió en la cama.','The wolf put on a bonnet and got into bed.'],
   ['Cuando llegó Caperucita, notó algo extraño.','When Little Red Riding Hood arrived, she noticed something strange.'],
   ['—Abuela, ¡qué orejas tan grandes tienes! —dijo.','“Grandmother, what big ears you have!” she said.'],
   ['—Son para oírte mejor —respondió el lobo.','“They are to hear you better,” replied the wolf.'],
   ['La niña vio sus dientes, reconoció al lobo y corrió hacia la puerta.','The girl saw his teeth, recognized the wolf, and ran toward the door.'],
   ['Un vecino oyó sus gritos y se acercó; el lobo huyó por la ventana.','A neighbor heard her cries and came closer; the wolf fled through the window.'],
   ['La abuela salió de su escondite y abrazó a Caperucita.','The grandmother came out of her hiding place and hugged Little Red Riding Hood.'],
   ['Las dos compartieron la merienda y agradecieron la ayuda del vecino.','The two shared their afternoon snack and thanked the neighbor for his help.']
  ],
  vocab:[['la caperuza','the hood'],['la cesta','the basket'],['el atajo','the shortcut'],['el escondite','the hiding place']],
  tip:'Había una vez is a familiar story opening. Then look for the completed events: dio, tomó, llegó, vio.',
  proTip:'Qué ... tan ... forms an exclamation: ¡Qué orejas tan grandes! means What big ears! Here tan is not a comparison with another person.',
  taglish:'Para oírte mejor = to hear you better. Te attaches to the infinitive oír. Se puso un gorro means put on a bonnet, not put a bonnet somewhere else.',
  questions:[['How does the wolf arrive first?',['He takes a train','He takes a shortcut','The girl carries him'],1,'El lobo tomó un atajo while she stopped for flowers.'],['Where is the grandmother in this version?',['In the forest','At the neighbor’s house','Hidden in a wardrobe'],2,'La abuela se escondió en un armario.'],['What makes Caperucita recognize the wolf?',['Seeing his teeth','Reading his note','Finding the basket'],0,'La niña vio sus dientes, reconoció al lobo.']]
 }
];
