import {useState} from 'react';
import {ArrowRight,Check} from '@phosphor-icons/react';
import {tracks} from './course-expansion';
export function CourseMap({lessons,progress,onOpen}){
 const [track,setTrack]=useState('Beginner');
 const selected=lessons.filter(l=>(l.track||'Beginner')===track);
 const count=selected.filter(l=>progress.completed.includes(l.id)).length;
 return <><div className="track-picker" aria-label="Course difficulty">{tracks.map(t=><button key={t} aria-pressed={track===t} onClick={()=>setTrack(t)}>{t}<small>{lessons.filter(l=>(l.track||'Beginner')===t).length} lessons</small></button>)}</div><p className="muted">{track==='Beginner'?'Start with words and phrases, then build your own sentences.':track==='Intermediate'?'Tell stories about the past and connect events with clearer grammar.':'Explore mood, hypotheses, and nuance with guided examples. These are focused lessons, not a complete advanced-level certification.'}</p><div className="course-summary"><span>{track} · Guided learning</span><strong>{count} / {selected.length} lessons completed</strong></div>{[...new Set(selected.map(l=>l.unit))].map((unit,u)=><section key={unit}><div className="section-kicker">UNIT {u+1}</div><h2>{unit}</h2><div className="lesson-list">{selected.filter(l=>l.unit===unit).map(l=><button key={l.id} className="lesson-link" onClick={()=>onOpen(lessons.indexOf(l))}><span className="lesson-no">{progress.completed.includes(l.id)?<Check/>:String(selected.indexOf(l)+1).padStart(2,'0')}</span><span><strong>{l.title}</strong><small>{l.meaning}</small></span><span className="lesson-time">{l.level||'A0–A1'}</span><ArrowRight/></button>)}</div></section>)}<div className="future"><h2>Learn, then use it.</h2><p>Visit Library → Stories or Conversations for reading at your level. Start with the Spanish, then reveal the English when you need it.</p><p className="muted">Difficulty labels guide your practice. They are not placement results or CEFR certification.</p></div></>;
}
