import {useEffect,useState} from 'react';
import {grammarLab} from './grammar-lab-data';
import {callSimulations} from './call-simulations';
import {StudySupport} from './StudySupport';
import './study-support.css';
import {practiceKey,readPractice,normalize} from './practice-state';
export function PracticeLab(){
 const [tab,setTab]=useState('Grammar'),[selected,setSelected]=useState(null),[saved,setSaved]=useState(readPractice),[error,setError]=useState('');
 function finish(kind,id){const next={...saved,[kind]:[...new Set([...saved[kind],id])]};setSaved(next);try{localStorage.setItem(practiceKey,JSON.stringify(next));setError('');}catch{setError('Practice completed, but this browser could not save it.');}}
 return <div className="practice-lab"><p>Start here for sentence construction: conjugations, pronouns, and realistic customer calls. Practice is self-paced.</p><div className="progress-actions">{['Grammar','BPO simulations'].map(t=><button className="secondary" aria-pressed={tab===t} key={t} onClick={()=>{setTab(t);setSelected(null);}}>{t}</button>)}</div>{error&&<p role="alert">{error}</p>}{selected?<><button className="text-button" onClick={()=>setSelected(null)}>← All {tab.toLowerCase()}</button>{tab==='Grammar'?<GrammarLesson key={selected.id} lesson={selected} onFinish={()=>finish('grammar',selected.id)}/>:<Call key={selected.id} scenario={selected} onFinish={()=>finish('simulations',selected.id)}/>}</>:<div>{(tab==='Grammar'?grammarLab:callSimulations).map(l=><button className="lesson-link" key={l.id} onClick={()=>setSelected(l)}><strong>{l.title}</strong><span>{saved[tab==='Grammar'?'grammar':'simulations'].includes(l.id)?'Practiced ✓':'Start practice →'}</span></button>)}</div>}</div>;
}
function GrammarLesson({lesson:l,onFinish}){
 const [step,setStep]=useState(0),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(null),[hint,setHint]=useState(false),[done,setDone]=useState(false);
 const t=l.tasks[step];
 return <article><h2>{l.title}</h2><p>{l.english}</p><p className="teaching-note"><strong>Taglish · how it works</strong><br/>{l.taglish}</p><p className="pattern">{l.formula}</p><div className="support-table-wrap"><table><thead><tr><th>Person / use</th><th>Spanish form</th><th>English</th></tr></thead><tbody>{l.table.map(([p,f,e])=><tr key={p}><td>{p}</td><td lang="es">{f}</td><td>{e}</td></tr>)}</tbody></table></div><h3>See how sentences are formed</h3>{l.examples.map(([es,en,tl])=><div className="teaching-note" key={es}><strong lang="es">{es}</strong><p>{en}</p><p>Taglish: {tl}</p><StudySupport spanish={es} english={en} tip={l.memory}/></div>)}<p><strong>Pro tip & memory cue:</strong> {l.memory}</p>{done?<div role="status"><h3>Lesson practiced ✓</h3><p>You completed all three model exercises. Try saying one new sentence aloud using the same pattern.</p><button className="secondary" onClick={()=>{setDone(false);setStep(0);setAnswer('');setFeedback(null);setHint(false);}}>Practice again</button></div>:<section><h3>Build your sentence · {step+1} of {l.tasks.length}</h3><p>{t.prompt}</p><p className="muted">This checks the requested model, not every valid Spanish translation. Accents matter. You can copy: á é í ó ú ü ñ.</p>{step===0&&<p>Word bank: {t.answer.split(' ').reverse().join(' · ')}</p>}<label htmlFor="lab-answer">Your Spanish sentence</label><textarea id="lab-answer" lang="es" value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback(null);}}/><button className="text-button" onClick={()=>setHint(!hint)}>{hint?'Hide support':'Hint and model'}</button>{hint&&<p>{t.hint}<br/><strong lang="es">{t.answer}</strong></p>}<button className="primary" disabled={!answer.trim()} onClick={()=>setFeedback(normalize(answer)===normalize(t.answer))}>Check sentence</button>{feedback!==null&&<div className="teaching-note" role="status"><strong>{feedback?'Matches the model.':'Compare the requested pattern and try again.'}</strong><p>Model: <span lang="es">{t.answer}</span></p><p>{t.why}</p><p>Taglish: {t.taglish}</p>{feedback&&<button className="primary" onClick={()=>{if(step===l.tasks.length-1){setDone(true);onFinish();}else{setStep(step+1);setAnswer('');setFeedback(null);setHint(false);}}}>{step===l.tasks.length-1?'Finish grammar lesson':'Next exercise'}</button>}</div>}</section>}</article>;
}
function Call({scenario:s,onFinish}){
 const [step,setStep]=useState(0),[draft,setDraft]=useState(''),[result,setResult]=useState(null),[done,setDone]=useState(false),[model,setModel]=useState(false);
 const [audio,setAudio]=useState('');
 useEffect(()=>()=>{window.speechSynthesis?.cancel();},[step]);
 function listen(){if(!window.speechSynthesis){setAudio('Audio is unavailable. Read the Spanish aloud instead.');return;}window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(s.turns[step].customer);speech.lang='es-MX';speech.rate=0.85;speech.onerror=()=>setAudio('Audio could not play. You can still practice aloud.');setAudio('Browser-generated Spanish audio');window.speechSynthesis.speak(speech);}
 const t=s.turns[step];const options=step%2?[false,true]:[true,false];
 return <article><h2>{s.title}</h2><p>{s.context}</p><p>Speak your reply aloud, then draft it. Drafts are self-assessed and stay only in this open exercise. Choose the response strategy to continue; this is a scripted simulation, not AI speech scoring.</p>{done?<div role="status"><h3>Call practiced ✓</h3><p>You practiced opening, empathy, clarification, action, and closing. Replay with your own name and wording.</p>{s.turns.map((x,i)=><div className="teaching-note" key={i}><strong>{x.goal}</strong><p lang="es">{x.model}</p><p>{x.english}</p><p>Taglish: {x.taglish}</p></div>)}<button className="secondary" onClick={()=>{setDone(false);setStep(0);setResult(null);setDraft('');setModel(false);}}>Replay call</button></div>:<section><p className="eyebrow">Turn {step+1} / {s.turns.length} · {t.goal}</p><h3 lang="es">Customer: {t.customer}</h3><p>{t.translation}</p><button className="secondary" onClick={listen}>Listen to customer</button>{audio&&<p role="status">{audio}</p>}<label htmlFor="call-draft">What would you say in Spanish?</label><textarea id="call-draft" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="text-button" onClick={()=>setModel(!model)}>{model?'Hide model':'Show model and sentence explanation'}</button>{model&&<StudySupport spanish={t.model} english={t.english} tip={t.why}/>}<h3>Choose your next response</h3>{options.map(correct=><button className="choice" key={String(correct)} onClick={()=>setResult(correct)}><span lang="es">{correct?t.model:t.bad[0]}</span><br/><span>{correct?t.english:t.bad[1]}</span></button>)}{result!==null&&<div role="status" className="teaching-note"><strong>{result?'Appropriate next step.':'Try a different approach.'}</strong><p>{result?t.why:t.bad[2]}</p><p>Taglish: {t.taglish}</p>{result&&<button className="primary" onClick={()=>{if(step===s.turns.length-1){setDone(true);onFinish();}else{setStep(step+1);setDraft('');setResult(null);setModel(false);}}}>{step===s.turns.length-1?'Finish call':'Next customer reply'}</button>}</div>}</section>}</article>;
}
