import {useState} from 'react';
import {ArrowLeft,ArrowRight,Check,SpeakerHigh} from '@phosphor-icons/react';
import {readings} from './reading-data';
import {tracks} from './course-expansion';
function readSaved(){try{const a=JSON.parse(localStorage.getItem('espanol-readings-v1'));return Array.isArray(a)?a:[];}catch{return [];}}
export function ReadingRoom({kind}){
 const [track,setTrack]=useState('Beginner'),[selected,setSelected]=useState(null),[translation,setTranslation]=useState(true),[answers,setAnswers]=useState({}),[checked,setChecked]=useState(false),[completed,setCompleted]=useState(readSaved),[status,setStatus]=useState('');
 const entries=readings.filter(r=>r.kind===kind&&r.track===track);
 function open(r){setSelected(r);setAnswers({});setChecked(false);setStatus('');window.scrollTo({top:0});}
 function listen(text){if(!window.speechSynthesis){setStatus('Audio is unavailable here. You can still read and practice aloud.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-MX';u.rate=.85;u.onerror=()=>setStatus('Audio could not play. Please read the text aloud or try again.');speechSynthesis.speak(u);setStatus('Browser-generated Spanish audio.');}
 function finish(){const next=[...new Set([...completed,selected.id])];setCompleted(next);try{localStorage.setItem('espanol-readings-v1',JSON.stringify(next));setStatus('Reading completed and saved on this browser.');}catch{setStatus('Reading completed, but this browser could not save it.');}}
 if(selected){const allCorrect=selected.questions.every((q,i)=>Number(answers[i])===q[2]);return <article className="reading-room"><button className="text-button" onClick={()=>{setSelected(null);window.speechSynthesis?.cancel();}}><ArrowLeft/>Back to {kind.toLowerCase()}</button><p className="section-kicker">{selected.track} · {selected.focus}</p><h2 className="reading-title" lang="es">{selected.title}</h2><p className="english-meaning">{selected.englishTitle}</p><div className="teaching-note"><strong>Before you read</strong><p>{selected.intro}</p>{selected.source&&<p><a href={selected.source[1]} target="_blank" rel="noreferrer">{selected.source[0]}</a></p>}</div><div className="reader-controls"><label><input type="checkbox" checked={translation} onChange={e=>setTranslation(e.target.checked)}/>Show English translations</label><button className="text-button" onClick={()=>listen(selected.lines.map(l=>l[0]).join(' '))}><SpeakerHigh/>Listen to the whole text</button></div><div className={'reading-lines '+(kind==='Conversations'?'dialogue-lines':'')}>{selected.lines.map(([es,en],i)=><div className="reading-line" key={es}><span className="line-number">{String(i+1).padStart(2,'0')}</span><div><p lang="es">{es}</p>{translation&&<p className="english-meaning">{en}</p>}</div><button className="icon-button" aria-label={'Listen to line '+(i+1)} onClick={()=>listen(es)}><SpeakerHigh size={18}/></button></div>)}</div><section><h3>Your vocabulary key</h3><dl className="vocab-key">{selected.vocab.map(([es,en])=><div key={es}><dt lang="es">{es}</dt><dd>{en}</dd></div>)}</dl></section><div className="teaching-note"><strong>Taglish explanation</strong><p>{selected.taglish}</p></div><div className="grammar-takeaways"><div><h3>Tip</h3><p>{selected.tip}</p></div><div><h3>Pro tip</h3><p>{selected.proTip}</p></div></div><section className="reading-check"><h3>Check your understanding</h3><p className="muted">Use evidence from the text. You can read it again.</p>{selected.questions.map(([prompt,options,answer,reason],i)=><fieldset key={prompt}><legend>{i+1}. {prompt}</legend>{options.map((o,j)=><label key={o}><input type="radio" name={'reading-q-'+i} checked={answers[i]===j} onChange={()=>{setAnswers({...answers,[i]:j});setChecked(false);}}/>{o}</label>)}{checked&&<div className={'feedback '+(answers[i]===answer?'success':'retry')}><strong>{answers[i]===answer?'Correct.':'Answer: '+options[answer]}</strong><p>{reason}</p></div>}</fieldset>)}<button className="primary" disabled={Object.keys(answers).length!==selected.questions.length} onClick={()=>setChecked(true)}>Check understanding<Check/></button>{checked&&allCorrect&&<button className="secondary" onClick={finish}>{completed.includes(selected.id)?'Reading completed':'Mark reading complete'}<Check/></button>}</section><p role="status" className="reader-status">{status}</p></article>;}
 return <div><div className="track-picker" aria-label="Reading difficulty">{tracks.map(t=><button key={t} aria-pressed={track===t} onClick={()=>setTrack(t)}>{t}</button>)}</div><p className="resource-intro">{entries.length} {kind.toLowerCase()} · bilingual reading, vocabulary, and comprehension</p><div className="reading-catalog">{entries.map(r=><button className="reading-card" key={r.id} onClick={()=>open(r)}><span className="section-kicker">{r.track} · {r.lines.length} {kind==='Stories'?'sentences':'turns'}</span><strong lang="es">{r.title}</strong><span>{r.englishTitle}</span><small>{r.focus}</small><span className="read-action">{completed.includes(r.id)?'Read again':'Start reading'}<ArrowRight size={18}/></span></button>)}</div></div>;
}

