import { expandedGrammar } from './course-expansion.js';
const verbRows = [
 ['ser','to be · identity','irregular','soy,eres,es,somos,sois,son','Soy estudiante.','I’m a student.','Identity, origin, classification, time, and many characteristics. Hindi universal rule ang permanent.'],
 ['estar','to be · state/location','irregular','estoy,estás,está,estamos,estáis,están','Estoy en casa.','I’m at home.','Use for states and locations of people/things. Events can use ser for location: La clase es aquí.'],
 ['tener','to have','irregular','tengo,tienes,tiene,tenemos,tenéis,tienen','Tengo hambre.','I’m hungry.','Tener ang gamit sa age at expressions tulad ng hambre. Literally “I have hunger.”'],
 ['ir','to go','irregular','voy,vas,va,vamos,vais,van','Voy a trabajar.','I’m going to work.','Ir a + infinitive gives a plan. Ir a + place describes going somewhere.'],
 ['hacer','to do / make','irregular','hago,haces,hace,hacemos,hacéis,hacen','Hago la tarea.','I do the homework.','Hago is the irregular yo form. La tarea can mean homework or a task.'],
 ['hablar','to speak','regular -ar','hablo,hablas,habla,hablamos,habláis,hablan','Hablo inglés.','I speak English.','Tanggal -ar, then add -o, -as, -a, -amos, -áis, -an.'],
 ['comer','to eat','regular -er','como,comes,come,comemos,coméis,comen','Comemos arroz.','We eat rice.','Tanggal -er. Nosotros uses -emos: comemos.'],
 ['vivir','to live','regular -ir','vivo,vives,vive,vivimos,vivís,viven','Vivo en Manila.','I live in Manila.','Regular -ir is like -er in many forms, but nosotros uses -imos.'],
 ['llamarse','to be called','reflexive','me llamo,te llamas,se llama,nos llamamos,os llamáis,se llaman','Me llamo Ana.','My name is Ana.','The small pronoun changes too: me, te, se, nos, os, se. Learn the pair.'],
 ['querer','to want / love','e → ie','quiero,quieres,quiere,queremos,queréis,quieren','Quiero agua.','I want water.','The stem changes except in nosotros and vosotros. Querer also means love in personal contexts.'],
 ['poder','can / to be able','o → ue','puedo,puedes,puede,podemos,podéis,pueden','Puedo ayudar.','I can help.','Use poder + infinitive. Puedo ayudar, not puedo ayudo.'],
 ['necesitar','to need','regular -ar','necesito,necesitas,necesita,necesitamos,necesitáis,necesitan','Necesito ayuda.','I need help.','Ayuda is a noun here: help. Necesito estudiar uses a verb: I need to study.'],
 ['aprender','to learn','regular -er','aprendo,aprendes,aprende,aprendemos,aprendéis,aprenden','Aprendo español.','I’m learning Spanish.','The Spanish simple present can describe what you are learning now or habitually.'],
 ['estudiar','to study','regular -ar','estudio,estudias,estudia,estudiamos,estudiáis,estudian','Estudio por la noche.','I study at night.','Por la noche means at night. Keep the phrase together.'],
 ['trabajar','to work','regular -ar','trabajo,trabajas,trabaja,trabajamos,trabajáis,trabajan','Trabajo en un hotel.','I work in a hotel.','Trabajo can also be a noun meaning work or job. The sentence tells you its role.'],
 ['beber','to drink','regular -er','bebo,bebes,bebe,bebemos,bebéis,beben','Bebo agua.','I drink water.','A regular -er verb. Agua means water.'],
 ['escribir','to write','regular -ir','escribo,escribes,escribe,escribimos,escribís,escriben','Escribo un mensaje.','I write a message.','Mensaje is masculine: un mensaje.'],
 ['leer','to read','regular -er','leo,lees,lee,leemos,leéis,leen','Leo un libro.','I read a book.','Two adjacent e letters are normal in forms such as lees.'],
 ['escuchar','to listen to','regular -ar','escucho,escuchas,escucha,escuchamos,escucháis,escuchan','Escucho música.','I listen to music.','No extra Spanish word for English “to” is needed before música.'],
 ['mirar','to look at / watch','regular -ar','miro,miras,mira,miramos,miráis,miran','Miro una foto.','I look at a photo.','Mirar emphasizes looking. Ver often means seeing.'],
 ['ver','to see','irregular yo','veo,ves,ve,vemos,veis,ven','Veo el mar.','I see the sea.','The yo form is veo. El mar means the sea.'],
 ['saber','to know · facts/skills','irregular yo','sé,sabes,sabe,sabemos,sabéis,saben','Sé cocinar.','I know how to cook.','Saber + infinitive means know how to do something. Keep the accent in sé.'],
 ['conocer','to know · familiarity','irregular yo','conozco,conoces,conoce,conocemos,conocéis,conocen','Conozco Manila.','I’m familiar with Manila.','Conocer is for familiarity with people/places. With a specific person: Conozco a Ana.'],
 ['decir','to say / tell','irregular','digo,dices,dice,decimos,decís,dicen','Digo la verdad.','I tell the truth.','Digo is the yo form; dices has e → i.'],
 ['venir','to come','irregular','vengo,vienes,viene,venimos,venís,vienen','Vengo de casa.','I’m coming from home.','Vengo = I come; voy = I go. Perspective matters.'],
 ['salir','to leave / go out','irregular yo','salgo,sales,sale,salimos,salís,salen','Salgo a las ocho.','I leave at eight.','Use a las + time for when something happens, except a la una.'],
 ['poner','to put','irregular yo','pongo,pones,pone,ponemos,ponéis,ponen','Pongo el libro aquí.','I put the book here.','Pongo is irregular. Aquí means here.'],
 ['dar','to give','irregular yo','doy,das,da,damos,dais,dan','Doy clases de español.','I teach Spanish classes.','Dar clases literally means give classes; natural English is teach classes.'],
 ['pedir','to ask for / order','e → i','pido,pides,pide,pedimos,pedís,piden','Pido un café.','I order a coffee.','Pedir asks for something; preguntar asks a question.'],
 ['preguntar','to ask · a question','regular -ar','pregunto,preguntas,pregunta,preguntamos,preguntáis,preguntan','Pregunto la hora.','I ask the time.','Use preguntar for information or questions. Use pedir for requests for things.'],
 ['dormir','to sleep','o → ue','duermo,duermes,duerme,dormimos,dormís,duermen','Duermo ocho horas.','I sleep eight hours.','Nosotros keeps the original stem: dormimos.'],
 ['sentir','to feel','e → ie','siento,sientes,siente,sentimos,sentís,sienten','Lo siento.','I’m sorry.','Lo siento is a useful fixed expression. Me siento bien = I feel well.'],
 ['preferir','to prefer','e → ie','prefiero,prefieres,prefiere,preferimos,preferís,prefieren','Prefiero té.','I prefer tea.','The second e in preferir changes in prefiero. Té has an accent when it means tea.'],
 ['pensar','to think / plan','e → ie','pienso,piensas,piensa,pensamos,pensáis,piensan','Pienso en mi familia.','I think about my family.','Pensar en means think about. Pienso estudiar means I plan to study.'],
 ['entender','to understand','e → ie','entiendo,entiendes,entiende,entendemos,entendéis,entienden','No entiendo.','I don’t understand.','A useful repair phrase. Add ¿Puedes repetir? to keep the conversation moving.'],
 ['empezar','to begin','e → ie','empiezo,empiezas,empieza,empezamos,empezáis,empiezan','Empiezo a estudiar.','I begin to study.','Empezar a + infinitive needs a.'],
 ['volver','to return','o → ue','vuelvo,vuelves,vuelve,volvemos,volvéis,vuelven','Vuelvo a casa.','I return home.','Volver a + infinitive means do something again: vuelvo a leer.'],
 ['encontrar','to find','o → ue','encuentro,encuentras,encuentra,encontramos,encontráis,encuentran','No encuentro mi libro.','I can’t find my book.','Natural English may say can’t find even though Spanish uses a negative present form.'],
 ['comprar','to buy','regular -ar','compro,compras,compra,compramos,compráis,compran','Compro pan.','I buy bread.','Pan means bread. Learn common verb + object combinations.'],
 ['pagar','to pay','regular present -ar','pago,pagas,paga,pagamos,pagáis,pagan','Pago con tarjeta.','I pay by card.','Con tarjeta = by card. Pagar is regular in this tense but has spelling changes in some other forms.'],
 ['tomar','to take / drink','regular -ar','tomo,tomas,toma,tomamos,tomáis,toman','Tomo el autobús.','I take the bus.','Tomar can also mean have a drink: tomo café.'],
 ['llevar','to carry / take / wear','regular -ar','llevo,llevas,lleva,llevamos,lleváis,llevan','Llevo una chaqueta.','I’m wearing a jacket.','Meaning depends on context. Llevo el libro a clase = I take the book to class.'],
 ['traer','to bring','irregular yo','traigo,traes,trae,traemos,traéis,traen','Traigo agua.','I’m bringing water.','Traer usually points toward a reference location; llevar away/to another place.'],
 ['abrir','to open','regular present -ir','abro,abres,abre,abrimos,abrís,abren','Abro la puerta.','I open the door.','Regular in the present. Its past participle is irregular: abierto.'],
 ['cerrar','to close','e → ie','cierro,cierras,cierra,cerramos,cerráis,cierran','Cierro la ventana.','I close the window.','La ventana = the window. Nosotros is cerramos, without the stem change.'],
 ['esperar','to wait / hope','regular -ar','espero,esperas,espera,esperamos,esperáis,esperan','Espero el autobús.','I’m waiting for the bus.','Esperar can mean wait for, hope, or expect. Here it means wait for.'],
 ['ayudar','to help','regular -ar','ayudo,ayudas,ayuda,ayudamos,ayudáis,ayudan','Ayudo a mi hermana.','I help my sister.','Use personal a before a specific person: a mi hermana.'],
 ['cocinar','to cook','regular -ar','cocino,cocinas,cocina,cocinamos,cocináis,cocinan','Cocino en casa.','I cook at home.','En casa means at home. No article is needed in this expression.'],
 ['caminar','to walk','regular -ar','camino,caminas,camina,caminamos,camináis,caminan','Camino al trabajo.','I walk to work.','A + el contracts to al: al trabajo.'],
 ['gustar','to be pleasing / like','agreement with liked thing','gusto,gustas,gusta,gustamos,gustáis,gustan','Me gustan los libros.','I like books.','For I like, usually use me gusta + singular/infinitive, me gustan + plural. The table agrees with the pleasing person/thing, NOT the person doing the liking.']
];
export const verbs=verbRows.map(([infinitive,meaning,type,forms,example,translation,note])=>({infinitive,meaning,type,forms:forms.split(','),example,translation,note}));
export const pronouns=[['yo','I'],['tú','you · informal'],['él / ella / usted','he / she / you · formal'],['nosotros / nosotras','we'],['vosotros / vosotras','you all · informal Spain'],['ellos / ellas / ustedes','they / you all']];
const baseGrammar=[
 {id:'sounds',title:'Sounds, stress & accents',level:'A0',taglish:'Limang vowel sounds: a, e, i, o, u. Mas consistent kaysa English, pero hindi lahat ng sounds ay eksaktong katulad ng Tagalog.',english:'Most words ending in a vowel, n, or s have stress on the next-to-last syllable; most others on the final syllable. A written accent can mark a different stress pattern and also distinguish some words.',formula:'ca-sa · ha-blar · ca-fé',examples:[['La casa.','The house.'],['Un café.','A coffee.'],['Sí, gracias.','Yes, thank you.']],tip:'H is usually silent. Ñ is a separate letter. Ll and y vary by region; don’t force your own name into a Spanish pronunciation.',mistake:'Si without an accent means if; sí means yes.'},
 {id:'articles',title:'Articles & noun gender',level:'A0',taglish:'Article ang maliit na word bago ang noun: el, la, un, una. Noun = pangalan ng tao, bagay, lugar, o idea. Learn el libro, hindi libro lang.',english:'Definite articles mean the: el, la, los, las. Indefinite articles mean a/an or some: un, una, unos, unas. They agree with the noun.',formula:'el libro → los libros · la casa → las casas',examples:[['El libro es pequeño.','The book is small.'],['La casa es grande.','The house is big.'],['Tengo una pregunta.','I have a question.']],tip:'-o often signals masculine and -a feminine, but learn exceptions: el día, la mano.',mistake:'Grammatical gender does not mean a table or book has a biological gender.'},
 {id:'pronouns',title:'Who does the action?',level:'A0',taglish:'Pronoun ay pamalit sa pangalan: yo = ako, tú = ikaw. Madalas puwedeng alisin dahil may clue na sa verb ending.',english:'Use yo, tú, él/ella/usted, nosotros/nosotras, and ellos/ellas/ustedes. Vosotros/vosotras is informal plural in much of Spain. Ustedes is the usual plural you in Latin America.',formula:'yo hablo → hablo',examples:[['Hablo español.','I speak Spanish.'],['¿Tú estudias aquí?','Do you study here?'],['Ustedes hablan inglés.','You all speak English.']],tip:'Usted is formal singular you but uses third-person verb forms. Tú is informal singular.',mistake:'Tú has an accent when it means you. Tu without an accent means your.'},
 {id:'present',title:'Present-tense verb endings',level:'A1 starter',taglish:'Conjugation = pagbabago ng verb para malaman kung sino ang gumagawa. Infinitive = dictionary form na ending -ar, -er, o -ir.',english:'For regular verbs, remove the final -ar/-er/-ir and add the present ending. Yo uses -o. Tú uses -as for -ar, and -es for -er/-ir. Irregular verbs must be learned separately.',formula:'hablar → habl + o → hablo',examples:[['Hablo español.','I speak Spanish.'],['Comemos arroz.','We eat rice.'],['Viven en Manila.','They live in Manila.']],tip:'The present can express habits and current situations. It does not always translate word for word into the English simple present.',mistake:'Yo hablar is not a complete conjugated statement meaning I speak. Say yo hablo.'},
 {id:'ser-estar',title:'Ser or estar?',level:'A1 starter',taglish:'Ser: identity, origin, classification. Estar: state at location ng tao o bagay. Huwag umasa sa permanent vs temporary lang.',english:'Ser describes identity, origin, classification, time, and many characteristics. Estar describes states and locations of people/things. Event locations commonly use ser. Some adjectives change meaning with the verb.',formula:'soy + identity · estoy + state / location',examples:[['Soy de Filipinas.','I’m from the Philippines.'],['Estoy cansado.','I’m tired. (masculine speaker)'],['La clase es aquí.','The class is here.'],['Manila está en Filipinas.','Manila is in the Philippines.']],tip:'Soy listo = I’m clever. Estoy listo = I’m ready. Learn the meaning of the whole phrase.',mistake:'A city’s location is stable but uses estar. This is why “permanent = ser” fails.'},
 {id:'tener',title:'Tener: age, hunger & more',level:'A0',taglish:'May expressions na tener ang gamit kahit I am sa English. Learn the phrase: tengo hambre, tengo sed, tengo veinte años.',english:'Tener means to have, but age and several physical sensations use tener in natural Spanish. Its yo form is tengo.',formula:'tengo + años / hambre / sed / sueño',examples:[['Tengo veinte años.','I’m twenty years old.'],['Tengo hambre.','I’m hungry.'],['Tengo sed.','I’m thirsty.'],['Tengo sueño.','I’m sleepy.']],tip:'Tengo calor = I feel hot. Tengo frío = I feel cold. Don’t translate every English I am as soy.',mistake:'Soy veinte años is incorrect for age; use tengo veinte años.'},
 {id:'gustar',title:'Gustar without the confusion',level:'A1 starter',taglish:'Ang bagay na gusto mo ang nagco-control ng gusta/gustan. Me tells us na sa akin pleasing ang bagay.',english:'Gustar usually follows indirect-object pronoun + gusta/gustan + the thing liked. Use gusta for a singular noun or infinitive, gustan for plural nouns.',formula:'me gusta + el café · me gustan + los libros',examples:[['Me gusta el café.','I like coffee.'],['Me gustan los libros.','I like books.'],['Me gusta leer.','I like reading.'],['¿Te gusta el té?','Do you like tea?']],tip:'Me, te, le, nos, os, les identify the experiencer. Gusta/gustan agree with the thing liked.',mistake:'Me gusto el café is wrong for I like coffee. Me gusto has a different meaning.'},
 {id:'hay',title:'Hay versus está',level:'A0',taglish:'Hay = meron. Está = location ng isang specific na bagay na alam na natin. Introduce it with hay, then locate it with está.',english:'Hay means there is or there are and stays unchanged for number. Está/están usually locate a known person or thing.',formula:'hay + a thing · the thing + está + place',examples:[['Hay un baño aquí.','There is a bathroom here.'],['El baño está allí.','The bathroom is there.'],['Hay dos libros.','There are two books.'],['Los libros están en la mesa.','The books are on the table.']],tip:'Use hay for both one and many. Use está singular and están plural for location.',mistake:'Hay dos libros, not están dos libros, when you simply mean there are two books.'},
 {id:'questions',title:'Questions & negatives',level:'A0',taglish:'No bago ang verb ang basic negative. Sa questions, gamitin ang question words at opening ¿. Hindi kailangan ng do/does.',english:'Qué = what; quién = who; dónde = where; cuándo = when; cómo = how; por qué = why; cuánto = how much. Use no before a conjugated verb for simple negation.',formula:'no + verb · ¿question word + verb …?',examples:[['No entiendo.','I don’t understand.'],['¿Dónde vives?','Where do you live?'],['¿Cuánto cuesta?','How much does it cost?'],['¿Por qué estudias español?','Why do you study Spanish?']],tip:'Por qué asks why. Porque answers because: Porque me gusta = Because I like it.',mistake:'Don’t add an English-style do: ¿Hablas español? is already Do you speak Spanish?'},
 {id:'agreement',title:'Adjectives that match',level:'A0',taglish:'Adjective = naglalarawan. Maraming adjectives ang nagbabago para tumugma sa gender at number ng noun.',english:'Many -o adjectives change to -a for feminine nouns. Add the appropriate plural ending for plural nouns. Adjectives such as grande do not change for gender.',formula:'pequeño / pequeña / pequeños / pequeñas',examples:[['El libro es pequeño.','The book is small.'],['La casa es pequeña.','The house is small.'],['Las casas son pequeñas.','The houses are small.'],['Los libros son grandes.','The books are big.']],tip:'Most descriptive adjectives often follow the noun, but placement can change meaning and emphasis.',mistake:'Las casas pequeño does not agree. Use las casas pequeñas.'},
 {id:'two-verbs',title:'Two verbs, one simple pattern',level:'A1 starter',taglish:'Kapag quiero, puedo, o necesito ang first verb, dictionary form ang next action. Isang verb lang ang babaguhin sa pattern na ito.',english:'With querer, poder, or necesitar followed directly by another action, conjugate the first verb and leave the second in its infinitive form.',formula:'quiero / puedo / necesito + infinitive',examples:[['Quiero aprender.','I want to learn.'],['Puedo ayudar.','I can help.'],['Necesito estudiar.','I need to study.']],tip:'Some other verbs need a preposition: empiezo a estudiar. Learn the complete pattern.',mistake:'Quiero aprendo is incorrect. Say quiero aprender.'},
 {id:'future',title:'Your first future sentences',level:'A1 starter',taglish:'Voy a + infinitive = I’m going to do something. Hindi kailangan agad ang future conjugation para makapagsabi ng plano.',english:'Use a conjugated form of ir followed by a and an infinitive to talk about a plan or intention. Voy, vas, va, vamos, vais, van are present forms of ir.',formula:'ir + a + infinitive',examples:[['Voy a estudiar mañana.','I’m going to study tomorrow.'],['Vamos a comer.','We’re going to eat.'],['¿Vas a trabajar?','Are you going to work?']],tip:'Mañana = tomorrow; esta noche = tonight. Add a time phrase when useful.',mistake:'Voy estudiar is missing a. Use voy a estudiar.'}
];

const phraseGroups={
 'Meet & connect':[['Hola.','Hello.','Simple greeting any time.'],['Buenos días.','Good morning.','Use in the morning.'],['Buenas tardes.','Good afternoon.','A polite afternoon greeting.'],['Buenas noches.','Good evening / good night.','Works as a greeting at night or a farewell.'],['¿Cómo te llamas?','What’s your name?','Informal singular you.'],['Me llamo James.','My name is James.','Palitan ang James ng pangalan mo.'],['Mucho gusto.','Nice to meet you.','A useful first-meeting phrase.'],['Soy de Filipinas.','I’m from the Philippines.','Origin: soy de + place.'],['Vivo en Manila.','I live in Manila.','Home location: vivo en + place.'],['¿Cómo estás?','How are you?','Informal singular.'],['Estoy bien, gracias.','I’m well, thank you.','Estar describes your state.'],['¿Y tú?','And you?','Return the question.']],
 'Keep talking':[['No entiendo.','I don’t understand.','No goes before entiendo.'],['¿Puedes repetir, por favor?','Can you repeat, please?','Informal singular request.'],['Más despacio, por favor.','More slowly, please.','Ask for a comfortable pace.'],['¿Qué significa esta palabra?','What does this word mean?','Esta palabra = this word.'],['¿Cómo se dice “salamat” en español?','How do you say “salamat” in Spanish?','Swap the quoted word for what you need.'],['Estoy aprendiendo español.','I’m learning Spanish.','Useful phrase; estoy aprendiendo is a progressive form.'],['Hablo un poco de español.','I speak a little Spanish.','Un poco de = a little.'],['¿Puedes escribirlo?','Can you write it down?','Escribirlo = to write it. Lo refers to the thing.'],['No sé.','I don’t know.','Sé is the yo form of saber.'],['Un momento, por favor.','One moment, please.','Buy time to think.']],
 'Café & restaurant':[['Un café, por favor.','A coffee, please.','Simple polite order.'],['Agua, por favor.','Water, please.','Agua = water.'],['Sin azúcar, por favor.','Without sugar, please.','Sin = without.'],['Con leche, por favor.','With milk, please.','Con = with.'],['La cuenta, por favor.','The bill, please.','Cuenta means bill here.'],['¿Cuánto cuesta?','How much does it cost?','For one item.'],['¿Puedo pagar con tarjeta?','Can I pay by card?','Puedo = I can.'],['Para llevar, por favor.','To go, please.','For takeaway food or drinks.'],['Para aquí.','For here.','Dine-in reply.'],['Está muy rico.','It’s very tasty.','Rico can mean tasty when describing food.']],
 'Everyday kindness':[['Gracias.','Thank you.','A little word worth using often.'],['Muchas gracias.','Thank you very much.','Muchas adds warmth.'],['De nada.','You’re welcome.','A reply to thanks.'],['Por favor.','Please.','Use with a request.'],['Perdón.','Sorry / excuse me.','For a small interruption or mistake.'],['Lo siento.','I’m sorry.','For an apology or sympathy.'],['Hasta luego.','See you later.','Common farewell.'],['Hasta mañana.','See you tomorrow.','Mañana = tomorrow here.']],
 'Get around':[['¿Dónde está el baño?','Where is the bathroom?','Specific place: está.'],['¿Dónde está la estación?','Where is the station?','Estación = station.'],['Voy al hotel.','I’m going to the hotel.','A + el becomes al.'],['A la derecha.','To the right.','Useful direction chunk.'],['A la izquierda.','To the left.','Learn as a phrase.'],['Todo recto.','Straight ahead.','Also hear derecho in some regions.'],['Necesito ayuda.','I need help.','Ayuda is the noun help.'],['¿Está lejos?','Is it far?','Lejos = far.'],['Estoy aquí.','I’m here.','Aquí = here.'],['Quiero ir a casa.','I want to go home.','Quiero + infinitive, then a casa.']]
};
export const phrases=Object.entries(phraseGroups).flatMap(([category,rows])=>rows.map(([spanish,english,note],i)=>({id:category+'-'+i,category,spanish,english,note})));

export const grammar=[...baseGrammar,...expandedGrammar];
