// Original scenario-based language training. Follow verified product and employer procedures.
function lab(id,category,title,objective,phrases,customer,steps,decision,practice,model,coaching,transfer){
 return {id:'work-lab-'+id,category,title,objective,level:'Intermediate',phrases,
  dialogue:customer.flatMap((line,i)=>[['Customer',...line],['Agent',...phrases[i].slice(0,2)]]),
  steps,decision,practice,model,coaching,transfer};
}
export const serviceLabs=[
 lab('delivery','CSR practice labs','A delivery says “delivered”—but is missing','Investigate a missing delivery without blaming the customer or promising a replacement.',[
  ['Entiendo que esperaba recibirlo hoy. Revisemos la información de entrega.','I understand you expected to receive it today. Let us review the delivery information.','Acknowledge the impact before asking the customer to repeat details.'],
  ['¿La dirección que aparece en su pedido es correcta?','Is the address shown on your order correct?','Use the approved verification flow and avoid reading private details aloud unnecessarily.'],
  ['Voy a solicitar una investigación de la entrega. Aún no puedo confirmar un reemplazo.','I am going to request a delivery investigation. I cannot confirm a replacement yet.','Only offer an investigation if it is an available action. A delivery status is evidence, not proof of receipt by this customer.']
 ],[['El sistema dice entregado, pero no recibí nada.','The system says delivered, but I received nothing.'],['Necesito saber dónde está mi pedido.','I need to know where my order is.'],['Sí, la dirección es correcta. ¿Me enviarán otro?','Yes, the address is correct. Will you send another one?']],
 ['Confirm the order and review the delivery event through approved tools.','Ask one neutral question about the recorded address; do not imply the customer is lying.','Explain the investigation process and the next verified contact step.'],
 {prompt:'The address is correct, but receipt is unconfirmed. Choose the best next statement.',options:[['Usted debe haber perdido el paquete.','You must have lost the package.'],['Voy a revisar las opciones de investigación disponibles.','I am going to review the available investigation options.'],['Le garantizo un reemplazo hoy.','I guarantee a replacement today.']],answer:1,why:'Investigate the evidence and available process. Neither blame nor an unapproved replacement guarantee follows from the known facts.'},
 'Say: I am going to review the delivery information.','Voy a revisar la información de entrega.','Voy a + infinitive describes your next action. Entrega means delivery.',
 'Now the customer says the address is wrong. Explain that you will check the correction options before promising a reroute.'),
 lab('wrong-item','CSR practice labs','The customer received the wrong product','Confirm the mismatch and explain the return or replacement process clearly.',[
  ['Lamento que haya recibido un producto diferente.','I am sorry you received a different product.','Haya recibido follows this expression of regret. Acknowledge what the customer reports.'],
  ['¿Qué modelo pidió y cuál recibió?','Which model did you order, and which did you receive?','Compare the order with the received item before choosing a return process.'],
  ['Voy a comprobar las opciones de cambio y explicarle los pasos.','I am going to check the exchange options and explain the steps to you.','Check eligibility, costs, and instructions; do not invent free shipping or tell the customer to discard the item.']
 ],[['Pedí unos audífonos y recibí otro modelo.','I ordered headphones and received a different model.'],['Los que llegaron no son los que necesito.','The ones that arrived are not the ones I need.'],['Pedí el modelo A y recibí el B. ¿Cómo lo cambio?','I ordered model A and received B. How do I exchange it?']],
 ['Identify the expected item and received item.','Review the applicable exchange procedure and any evidence needed.','Explain one step at a time and ask the customer to confirm the next action.'],
 {prompt:'You have confirmed a model mismatch but have not checked the return terms. What do you say?',options:[['Puede tirarlo; le enviaremos otro gratis.','You can throw it away; we will send another for free.'],['No hay nada que hacer.','Nothing can be done.'],['Primero verificaré las condiciones del cambio.','First I will verify the exchange terms.']],answer:2,why:'A confirmed mismatch does not establish the exact remedy or shipping conditions. Verify those before promising them.'},
 'Ask: Which model did you receive?','¿Qué modelo recibió?','Recibió is the past usted form; recibo means I receive.',
 'The replacement option is unavailable in this fictional scenario. Offer to explain the verified alternatives without pressuring the customer.'),
 lab('plan-fit','CSR practice labs','Compare plans without overselling','Find the customer’s need, compare relevant terms, and confirm an informed choice.',[
  ['¿Qué necesita hacer con el servicio?','What do you need to do with the service?','Start with the task the customer needs, not the most expensive plan.'],
  ['Comparemos el precio, lo que incluye y las condiciones de renovación.','Let us compare the price, what is included, and the renewal terms.','Mention relevant recurring charges and restrictions from the actual plan information.'],
  ['No cambiaré su plan hasta que confirme la opción que prefiere.','I will not change your plan until you confirm the option you prefer.','Asking about a plan is not permission to change it.']
 ],[['Quiero un plan más barato.','I want a cheaper plan.'],['Solo uso el servicio para mensajes.','I only use the service for messages.'],['¿Me puede explicar las opciones antes de cambiarlo?','Can you explain the options before changing it?']],
 ['Ask which features matter and what the customer wants to spend.','Compare only verified prices, features, limitations, and renewal conditions.','Restate the chosen option and obtain the required confirmation before any change.'],
 {prompt:'The customer asks whether a cheaper plan exists. What is the appropriate action?',options:[['Explique las opciones verificadas y espere la elección del cliente.','Explain verified options and wait for the customer’s choice.'],['Cambie el plan de inmediato porque más barato siempre es mejor.','Switch immediately because cheaper is always better.'],['Evite mencionar las limitaciones.','Avoid mentioning limitations.']],answer:0,why:'The customer needs a comparison, not an automatic account change. Explain limitations and confirm the choice.'},
 'Ask: What do you need to do with the service?','¿Qué necesita hacer con el servicio?','Necesita hacer combines a conjugated verb and an infinitive. Keep the question open.',
 'The cheaper plan lacks a feature the customer uses. Explain that tradeoff and let the customer decide.'),
 lab('supervisor','CSR practice labs','Handle a supervisor request professionally','Acknowledge the request, explain the escalation path, and preserve the customer’s story.',[
  ['Entiendo que desea hablar con un supervisor.','I understand you would like to speak with a supervisor.','Do not argue about whether the customer deserves escalation.'],
  ['Voy a comprobar la disponibilidad y explicarle cómo continuar.','I am going to check availability and explain how to proceed.','Do not claim immediate availability if you have not verified it.'],
  ['Dejaré un resumen de su solicitud para que no tenga que repetir todo.','I will leave a summary of your request so you do not have to repeat everything.','Document the facts and desired outcome; follow the actual handoff process.']
 ],[['Quiero hablar con su supervisor.','I want to speak with your supervisor.'],['No quiero volver a explicar el problema.','I do not want to explain the problem again.'],['¿La otra persona sabrá lo que pasó?','Will the other person know what happened?']],
 ['Acknowledge the requested escalation without becoming defensive.','Check the approved route and actual availability.','Summarize the issue, previous actions, and requested outcome for the next owner.'],
 {prompt:'No supervisor is immediately available. Which statement is best?',options:[['No puede hablar con nadie más.','You cannot speak with anyone else.'],['Voy a verificar las opciones de seguimiento disponibles.','I am going to verify the available follow-up options.'],['Le llamarán en cinco minutos, seguro.','They will definitely call you in five minutes.']],answer:1,why:'Check the real follow-up process. Neither blocking escalation nor inventing a callback promise is justified.'},
 'Say: I understand you would like to speak with a supervisor.','Entiendo que desea hablar con un supervisor.','Desea is a courteous usted form. Acknowledge the request without promising the supervisor’s decision.',
 'Practice summarizing a disputed charge for the supervisor in two sentences: what the customer reports and what has been checked.'),
 lab('callback','CSR practice labs','Arrange a callback precisely','Confirm the contact route, date, time zone, and reason for follow-up.',[
  ['¿En qué horario puede recibir la llamada?','At what time can you receive the call?','Offer only the scheduling options actually supported by your team.'],
  ['¿A qué zona horaria se refiere?','Which time zone do you mean?','Do not assume that you and the customer share a time zone.'],
  ['Voy a confirmar la disponibilidad antes de programarla.','I am going to confirm availability before scheduling it.','A requested time is not a confirmed appointment.']
 ],[['¿Me pueden llamar mañana por la tarde?','Can you call me tomorrow afternoon?'],['A las tres estaría bien.','Three o’clock would work.'],['A la hora de Ciudad de México.','Mexico City time.']],
 ['Ask for a suitable time and verify the approved callback channel.','State the calendar date, time, and named time zone unambiguously.','Check availability, confirm only the booked arrangement, and document its purpose.'],
 {prompt:'The customer says “tomorrow at three.” What still needs clarification?',options:[['Nada; prográmela en su propia zona horaria.','Nothing; schedule it in your own time zone.'],['Pida su contraseña.','Ask for their password.'],['Confirme la fecha, si es por la mañana o por la tarde, y la zona horaria.','Confirm the date, morning or afternoon, and time zone.']],answer:2,why:'Relative dates and unqualified times can cause missed calls. Clarify them before booking.'},
 'Ask: Which time zone do you mean?','¿A qué zona horaria se refiere?','Referirse a means to refer to. Do not compute an offset from memory when booking a real call.',
 'The requested time is unavailable. Offer two verified alternatives and ask which works, without booking either prematurely.'),
 lab('currency','CSR practice labs','Resolve a confusing amount','Confirm currency, decimal amounts, billing period, and the customer’s concern.',[
  ['Para evitar confusiones, ¿en qué moneda aparece el importe?','To avoid confusion, in which currency does the amount appear?','A currency symbol alone may be ambiguous. Ask for the currency name.'],
  ['¿Ese total corresponde a un mes o a varios meses?','Does that total cover one month or several months?','Separate billing period from payment date.'],
  ['Voy a comparar el total con el desglose de ese período.','I am going to compare the total with the breakdown for that period.','Read decimals and currency clearly; do not assume that punctuation conventions match yours.']
 ],[['Me dijeron cien, pero veo doscientos en la factura.','They told me one hundred, but I see two hundred on the bill.'],['Aparece en pesos mexicanos.','It appears in Mexican pesos.'],['Parece que incluye dos meses.','It looks like it includes two months.']],
 ['Confirm the currency and full amount.','Check the exact dates covered and each line item.','Explain the verified calculation and ask whether the difference is now clear.'],
 {prompt:'The total is double the expected monthly price. What should you do before calling it an error?',options:[['Revise el período y el desglose de cargos.','Check the covered period and itemized charges.'],['Prometa quitar la mitad.','Promise to remove half of it.'],['Suponga que deben ser impuestos.','Assume it must be taxes.']],answer:0,why:'The same total can have different causes. Verify the billing period and line items instead of guessing.'},
 'Ask: In which currency does the amount appear?','¿En qué moneda aparece el importe?','Moneda means currency here. Importe means amount, not import.',
 'Explain a fictional bill of two monthly charges of one hundred Mexican pesos each. State the period and total in Spanish.'),
 lab('slow-connection','TSR practice labs','Slow connection or complete disconnection?','Separate symptoms and isolate the affected device, location, or service.',[
  ['¿La conexión es lenta o se interrumpe por completo?','Is the connection slow, or does it disconnect completely?','Different symptoms suggest different next questions.'],
  ['¿Ocurre también en otro dispositivo conectado a la misma red?','Does it also happen on another device connected to the same network?','A comparison helps narrow the scope; it does not prove a cause by itself.'],
  ['Comparemos el resultado cerca del enrutador, si puede hacerlo.','Let us compare the result near the router, if you can do so.','Check whether the comparison is practical; never insist that a customer move equipment unsafely.']
 ],[['Internet funciona muy mal.','The internet works very poorly.'],['Los videos tardan en cargar, pero no se desconecta.','Videos take a long time to load, but it does not disconnect.'],['Solo pasa con mi teléfono cuando estoy lejos del enrutador.','It only happens on my phone when I am far from the router.']],
 ['Clarify slow performance versus a dropped connection.','Compare another device or service while keeping track of what changed.','If location appears relevant, compare in a practical nearby location before making a diagnosis.'],
 {prompt:'Only one phone is slow in one room. What is the best next step?',options:[['Restablezca todos los dispositivos de fábrica.','Restore all devices to factory settings.'],['Compare la conexión del mismo teléfono en otro lugar.','Compare the same phone’s connection in another location.'],['Declare una interrupción nacional confirmada.','Declare a confirmed nationwide outage.']],answer:1,why:'Change one relevant variable and observe the result. A single-device, location-dependent symptom does not establish a widespread outage.'},
 'Ask: Is the connection slow?','¿La conexión es lenta?','Lenta agrees with conexión. Ask the customer to describe the symptom before naming a cause.',
 'Now every device fails everywhere in the home. Ask a question that distinguishes a Wi-Fi link from internet access, then check service status.'),
 lab('app-crash','TSR practice labs','An app closes unexpectedly','Find a reproducible trigger and avoid losing local data.',[
  ['¿La aplicación se cierra al abrirla o al realizar una acción específica?','Does the app close when you open it or when you perform a specific action?','The trigger is more informative than the general phrase it does not work.'],
  ['Antes de repetir la prueba, guarde los cambios que pueda.','Before repeating the test, save any changes you can.','Do not ask for repeated crashes that could destroy unsaved work.'],
  ['Voy a registrar la versión y el paso exacto en el que se cierra.','I am going to record the version and the exact step where it closes.','Use verified product guidance for updates or recovery. Reinstallation can remove locally stored data.']
 ],[['La aplicación se cierra sola.','The app closes by itself.'],['Se cierra cuando intento adjuntar una foto.','It closes when I try to attach a photo.'],['Ya guardé lo que pude. Sigue cerrándose al adjuntar la foto.','I saved what I could. It still closes when I attach the photo.']],
 ['Identify the action, app version, device, and when the problem began.','Protect unsaved work and follow the product’s least disruptive approved checks.','Capture the reproducible steps and escalate with the observed result if unresolved.'],
 {prompt:'The app contains unsynced notes. Should you immediately uninstall it?',options:[['Sí, eliminar datos siempre es inofensivo.','Yes, deleting data is always harmless.'],['Sí, sin explicar el efecto.','Yes, without explaining the effect.'],['Primero verifique las opciones de copia o recuperación y los efectos de eliminarla.','First verify backup or recovery options and the effects of removal.']],answer:2,why:'Reinstallation may remove local data. Confirm the product-specific consequences and customer agreement before disruptive actions.'},
 'Say: The app closes when I try to attach a photo.','La aplicación se cierra cuando intento adjuntar una foto.','Se cierra describes it closing; intento adjuntar means I try to attach.',
 'The crash happens only with one file. Ask about the file type and size without requesting private content.'),
 lab('notifications','TSR practice labs','Notifications do not arrive','Distinguish message delivery from notification display and sound.',[
  ['¿El mensaje aparece cuando abre la aplicación?','Does the message appear when you open the app?','If the message is present, delivery and notification display may be separate issues.'],
  ['¿Falta el aviso en pantalla, el sonido o ambos?','Is the on-screen alert missing, the sound, or both?','Ask which signal is missing before changing settings.'],
  ['Revisemos los permisos de notificación de esta aplicación.','Let us review this app’s notification permissions.','Use instructions for the actual device; avoid turning off unrelated security controls.']
 ],[['No me llegan los mensajes.','My messages are not coming through.'],['Sí aparecen al abrir la aplicación.','They do appear when I open the app.'],['No veo el aviso ni escucho el sonido.','I do not see the alert or hear the sound.']],
 ['Check whether content arrives inside the app.','Clarify whether visual alerts, sound, or both are missing.','Review relevant app and device notification settings, then test with a non-sensitive message.'],
 {prompt:'Messages are present inside the app but no alert appears. What should you investigate next?',options:[['Los permisos y modos de notificación del dispositivo.','Notification permissions and relevant device notification modes.'],['Suponga que se borraron todos los mensajes.','Assume all messages were deleted.'],['Pida que compre un teléfono nuevo.','Ask the customer to buy a new phone.']],answer:0,why:'The observed problem concerns alerts. Focus on that layer before proposing unrelated or costly actions.'},
 'Ask: Does the message appear when you open the app?','¿El mensaje aparece cuando abre la aplicación?','Abre is the usted form here. The question helps separate delivery from notification behavior.',
 'Only sound is missing; the on-screen alert works. Ask a narrower follow-up and explain what you will test.'),
 lab('audio','TSR practice labs','The customer cannot be heard on a call','Check the direction of the audio problem and the selected microphone.',[
  ['¿Usted no escucha a la otra persona, o la otra persona no le escucha?','Can you not hear the other person, or can the other person not hear you?','Separate incoming sound from outgoing microphone audio.'],
  ['¿Qué micrófono está seleccionado en la aplicación?','Which microphone is selected in the app?','A connected headset and the built-in microphone may be different inputs.'],
  ['Hagamos una prueba breve con el micrófono seleccionado.','Let us run a brief test with the selected microphone.','Explain the test and use non-sensitive speech; do not claim permission alone guarantees working audio.']
 ],[['No funciona el audio de la llamada.','The call audio does not work.'],['Yo escucho, pero la otra persona no me escucha.','I can hear, but the other person cannot hear me.'],['Aparece el micrófono del equipo, pero estoy usando audífonos con micrófono.','The built-in microphone appears, but I am using a headset.']],
 ['Identify whether input, output, or both are affected.','Check mute status, selected input, and relevant app permission using the correct product instructions.','After an agreed change, test the same call function and ask the customer to report the result.'],
 {prompt:'The customer hears others, but others cannot hear the customer. Which path should you investigate first?',options:[['Solo el brillo de la pantalla.','Only the screen brightness.'],['La entrada del micrófono, el silencio y el permiso.','Microphone input, mute status, and permission.'],['Solo el volumen de los altavoces.','Only speaker volume.']],answer:1,why:'The reported direction points to outgoing audio. Speaker volume controls incoming sound and does not explain this symptom by itself.'},
 'Ask: Which microphone is selected in the app?','¿Qué micrófono está seleccionado en la aplicación?','Está seleccionado describes a selection state. Micrófono needs its written accent.',
 'Reverse the situation: the customer cannot hear others, but others hear them. Ask about the selected speaker or headset output.'),
 lab('sync','TSR practice labs','A file is missing on the second device','Distinguish local saving, synchronization, and backup.',[
  ['¿El archivo sigue visible en el dispositivo original?','Is the file still visible on the original device?','Locate the known copy before changing or deleting anything.'],
  ['¿Ambos dispositivos usan la misma cuenta?','Do both devices use the same account?','Ask the customer to check the account through the approved interface; do not request a password.'],
  ['Antes de hacer cambios, confirmemos dónde está guardada la copia disponible.','Before making changes, let us confirm where the available copy is saved.','Sync can propagate changes or deletions. Do not assume it is an independent backup.']
 ],[['Guardé el archivo, pero no aparece en mi otro equipo.','I saved the file, but it does not appear on my other device.'],['Sí, todavía lo veo en el primer equipo.','Yes, I can still see it on the first device.'],['No estoy seguro de que sea la misma cuenta.','I am not sure it is the same account.']],
 ['Identify the available copy and avoid actions that might remove it.','Compare account, save location, and sync status using verified product guidance.','Confirm the file appears on the target device before declaring success.'],
 {prompt:'A file exists locally but is missing on another device. What should you avoid?',options:[['Comprobar la cuenta en ambos dispositivos.','Checking the account on both devices.'],['Comprobar dónde se guardó el archivo.','Checking the file’s saved location.'],['Borrar la única copia conocida para forzar la sincronización.','Deleting the only known copy to force synchronization.']],answer:2,why:'Preserve the available copy. Deleting it may lose data or propagate deletion rather than repair synchronization.'},
 'Ask: Do both devices use the same account?','¿Ambos dispositivos usan la misma cuenta?','Ambos means both. Usan is plural because dispositivos is plural.',
 'The accounts match, but the file was saved in a local folder. Explain the difference without promising that every folder syncs automatically.'),
 lab('bug-report','TSR practice labs','Escalate a reproducible bug','Turn a vague complaint into a useful technical report and customer update.',[
  ['¿Qué esperaba que ocurriera y qué ocurrió en realidad?','What did you expect to happen, and what actually happened?','Capture expected versus actual behavior before naming the cause.'],
  ['¿Puede indicar los pasos sin incluir datos privados?','Can you describe the steps without including private information?','Use a non-sensitive test example or redacted evidence.'],
  ['Enviaré los pasos y el resultado al equipo técnico; aún no hay una fecha de solución confirmada.','I will send the steps and result to the technical team; there is no confirmed fix date yet.','A useful escalation includes environment, version, steps, impact, and attempted checks.']
 ],[['El botón Guardar no sirve.','The Save button does not work.'],['Esperaba guardar el formulario, pero vuelve a la página anterior.','I expected to save the form, but it returns to the previous page.'],['Abro el formulario, completo los campos y pulso Guardar. Pasa siempre.','I open the form, fill in the fields, and press Save. It happens every time.']],
 ['Record the expected behavior, actual result, frequency, and impact.','Gather reproducible steps and the relevant environment without credentials or private form contents.','Route to the correct owner, give a case reference when available, and distinguish an update from a fix promise.'],
 {prompt:'The issue is reproducible, but the technical team has not estimated a fix. What should you tell the customer?',options:[['Documentaré el problema y confirmaré el proceso de seguimiento disponible.','I will document the issue and confirm the available follow-up process.'],['Seguro que estará resuelto mañana.','It will definitely be fixed tomorrow.'],['El cliente causó el error.','The customer caused the bug.']],answer:0,why:'Communicate what you can verify and own the handoff. Reproduction alone does not establish blame or a repair deadline.'},
 'Ask: What did you expect to happen?','¿Qué esperaba que ocurriera?','Esperaba que uses ocurriera here to describe an expected outcome. Keep observed behavior separate from a guessed cause.',
 'Write a four-line bug summary in Spanish: expected result, actual result, reproduction steps, and next owner. Practice saying it without reading.')
];
