import {verbs} from './reference-data.js';
import {getForms,tenseInfo} from './verb-tenses.js';

const rules=[
 [/\b(?:a ver|entonces|de acuerdo|por cierto|de hecho|mejor dicho|en fin|o sea)\b/i,'conversation marker + message','Ang a ver, entonces, de acuerdo, por cierto, de hecho, mejor dicho, en fin, at o sea ay nag-oorganize ng usapan. Hindi pare-pareho ang purpose: a ver introduces checking, entonces a next step, por cierto a side topic, at mejor dicho a correction. Hindi sila automatic na kailangan sa bawat sentence.','Conversation markers organize a message. A ver can introduce checking; entonces a next step; por cierto a side topic; mejor dicho a correction. Choose a marker for its function, not just to fill silence.','Say the message once without the marker, then add it only if its purpose fits.'],
 [/\b(?:me di cuenta)\b/i,'darse cuenta de + what was noticed','Me di cuenta = I realized. Di ang past yo form ng dar, pero ibang meaning ang buong expression na darse cuenta de. Hindi literal na “gave an account” dito.','Darse cuenta de means to realize or notice. Me di cuenta is its preterite yo form. Learn de with the expression when adding what you realized.','Me di cuenta DE + the issue.'],
 [/\b(?:lo siento)\b/i,'lo + siento: an apology or sympathy','Lo siento = I am sorry. Siento ang yo form ng sentir, at lo ang bagay o sitwasyong tinutukoy. Ang buong chunk ay apology o sympathy depende sa context.','Lo siento expresses an apology or sympathy. Siento is the present yo form of sentir; lo refers to the situation.','Learn lo siento as a whole phrase; do not translate each word separately.'],
 [/\b(?:llevo|lleva|llevamos) .+ (?:ando|iendo)\b/i,'llevar + duration + gerund','Llevo dos años estudiando = dalawang taon na akong nag-aaral. Llevar + duration + gerund ang continuing activity. Iba ito sa llevo una bolsa, na “I carry a bag.”','Llevar + duration + gerund describes an activity continuing over time. Distinguish this from llevar + an object, meaning to carry or bring.','Duration goes between llevo and the -ndo action.'],
 [/\b(?:vivía|había|estaba|esperaba|miraba)\b/i,'imperfect: background, habit, or ongoing situation','Ang vivía, había, estaba, esperaba, at miraba ay imperfect forms. Background o ongoing situation ang viewpoint; hindi nito ibig sabihin na walang katapusan ang action. Para sa regular -ar: -aba; sa -er/-ir: -ía.','Imperfect forms can describe background, habits, or situations in progress. Regular -ar uses -aba endings; -er/-ir uses -ía endings. Some forms such as estaba have their own stem.','Ask what the situation was like, not only what happened next.'],
 [/\b(?:terminé|compré|busqué|dejé|alcancé|olvidó|ocurrió|dijo|pudo)\b/i,'preterite: a completed event','Ang terminé, compré, busqué, at dejé ay completed past yo forms. Regular -ar yo ending ay -é; may spelling adjustment sa busqué para mapanatili ang tunog. Ang dijo at pudo ay irregular—tingnan ang kanilang forms, huwag hulaan.','The preterite presents an event as a completed whole. Regular -ar yo ends in -é; busqué changes spelling to preserve pronunciation. Dijo and pudo are irregular.','Compare compro / compré: present versus completed past.'],
 [/\b(?:revisaré|cerrará|intentaré|serán)\b/i,'future endings and context','Sa regular future, infinitive + ending: revisar + é = revisaré; cerrar + á = cerrará. May gamit ding supposition, tulad ng serán las ocho: probably eight o’clock. Context ang magdidikta kung future o guess.','Regular future forms retain the infinitive and add endings. The future may also express conjecture about the present, as in serán las ocho.','Keep the infinitive for a regular future; check irregular stems separately.'],
 [/\bno hables\b/i,'negative tú command: no + subjunctive form','Habla ang affirmative tú command; no hables ang negative. Hindi sapat na idagdag lang ang no sa habla. Present subjunctive form ang gamit sa negative tú command na ito.','Habla is an affirmative tú command; no hables uses the present subjunctive form for a negative tú command.','Say the pair: habla / no hables.'],
 [/\b(?:voy|va|vas|vamos|van) (?:al|a la|a los|a las)\b/i,'ir + a + destination','Voy = I go; va = he/she/usted goes. Ang a + el ay nagiging al, pero a la ay hiwalay. Lugar ang kasunod dito: voy al hotel, voy a la estación.','Ir + a + a place expresses going to a destination. A + el contracts to al; a la does not contract.','A + el = al. Keep a la separate.'],
 [/\bsi (?:hubiera|hubieras|hubiéramos|hubieran)\b/i,'si + past perfect subjunctive → conditional perfect','Sa si hubiera estudiado, iniimagine ang ibang nakaraan. Ang result na habría aprobado ay “would have passed.” Hindi ito report na talagang nangyari.','Si hubiera estudiado, habría aprobado imagines a different past condition and result: if I had studied, I would have passed.','Pair hubiera + participle with habría + participle for this model.'],
 [/\bsi (?:tuviera|tuvieras|tuviéramos|tuvieran)\b/i,'si + imperfect subjunctive → conditional','Si tuviera tiempo = kung may oras ako, bilang imagined situation. Viajaría = I would travel. Tuviera ang condition, viajaría ang result; huwag gamitin ang future ending sa halimbawang ito.','Si tuviera tiempo, viajaría pairs an imagined condition with a conditional result. Tuviera and viajaría do different jobs.','Condition: tuviera. Result: viajaría.'],
 [/\b(?:no creo que|ojalá|me alegra que|lamento que|para que|como si)\b/i,'a trigger phrase + a dependent clause','Ang no creo que, ojalá, me alegra que, lamento que, para que, at como si ay may patterns na nangangailangan ng subjunctive. Hindi lang “uncertain” ang dahilan: puwedeng emotion, purpose, wish, o comparison. Tingnan din ang panahon ng main clause.','These expressions introduce patterns commonly requiring subjunctive. The reason may be doubt, a wish, emotion, purpose, or a hypothetical comparison; the tense also depends on context.','Learn the trigger and its clause together, not the verb ending alone.'],
 [/\bme gustaría\b/i,'me + gustaría + infinitive','Me gustaría = I would like. Gustaría ay conditional ng gustar; ang infinitive na kasunod ang gusto mong gawin. Ang me ay “to me,” hindi ang subject ng gustar.','Me gustaría + infinitive expresses a polite wish. Gustaría is conditional; the action expressed by the infinitive is what would please you.','Me gustaría + viajar / aprender / practicar.'],
 [/\b(?:acabo|acabas|acaba|acabamos|acaban) de\b/i,'acabar de + infinitive','Acabo de llegar = kararating ko lang. Present ang acabo pero recent past ang meaning ng buong pattern. Ang llegar ay infinitive, hindi llegó.','Acabar de + infinitive in the present describes a very recent action: acabo de llegar means I have just arrived.','Remember de between acabo and the action.'],
 [/\b(?:dejó|dejé|dejaron) de\b/i,'dejar de + infinitive','Dejó de responder = tumigil sa pag-respond. Dejar de ang whole pattern para sa stopping an action. Ang dejó ay completed past; infinitive ang responder.','Dejar de + infinitive means to stop doing something. Dejó de responder means it stopped responding.','Stopping an action: dejar DE + verb.'],
 [/\b(?:vuelvo|vuelve|volvió|volví) a\b/i,'volver a + infinitive','Vuelvo a intentarlo = susubukan ko ulit. Volver a + infinitive ang repetition. Ang lo sa intentarlo ay object na idinugtong sa infinitive.','Volver a + infinitive means to do something again. An object pronoun can attach to the infinitive, as in intentarlo.','Again = volver A + action.'],
 [/\b(?:sigo|sigue|seguimos|siguen)\b/i,'seguir + -ndo / description','Sigo estudiando = nagpapatuloy akong mag-aral. Kapag action in progress ang ibig sabihin, gerund na -ando/-iendo ang kasunod. Pero sigue visible ay “remains visible”: adjective iyon, hindi gerund.','Seguir + gerund means to keep doing something. Seguir + an adjective can mean to remain in a state.','Sigo estudiando; sigue visible. Read what follows seguir.'],
 [/\b(?:solía|solías|solíamos|solían)\b/i,'soler in imperfect + infinitive','Solía jugar = I used to play. Imperfect ang solía; infinitive ang jugar. Habit sa nakaraan ang focus, hindi isang completed event lang.','Solía + infinitive describes a past habit: solía jugar means I used to play.','Past habit: solía + action.'],
 [/\b(?:me levanto|te levantas|se levanta|me siento|se siente)\b/i,'pronoun + matching verb form','Ipares ang pronoun at verb: me levanto = I get up; te levantas = you get up. Sa me siento triste, “I feel sad” ang meaning. Hindi puwedeng basta alisin ang me o te nang hindi tinitingnan ang meaning.','Pronominal expressions keep their person pronoun with the verb: me levanto, te levantas. Me siento triste means I feel sad.','Practice the pronoun and verb as one chunk.'],
 [/\b(?:lo veo|se lo doy|te lo explico)\b/i,'object pronouns + verb','Ang lo ay object, halimbawa “it” o “him,” depende sa context. Sa se lo doy, se ang recipient at lo ang ibinibigay; nauuna ang recipient pronoun. Sa te lo explico, sa iyo ko ipinapaliwanag iyon.','Object pronouns precede a conjugated verb. In se lo doy, se marks the recipient (replacing le/les before lo), and lo is the thing given.','Recipient before thing: te lo / se lo.'],
 [/\b(?:hace|hacía) (?:mucho |buen )?(?:frío|calor|sol|tiempo)\b/i,'hacer + weather expression','Hace frío = malamig ang panahon; hace calor = mainit. Hacer ang verb ng weather expression na ito. Hacía ang past background form, tulad ng hacía frío.','Use hacer in these weather expressions: hace frío / hace calor. Hacía describes the weather as past background.','Weather chunk: hace frío, not es frío for this meaning.'],
 [/\b(?:tengo|tienes|tiene|tenemos|tienen)\b/i,'tener + what is possessed / an expression','Tener = to have. Tengo para sa yo, tienes para sa tú, tiene para sa él/ella/usted. Sa age at ilang feelings, tener din: tengo veinte años, tengo hambre. Hindi lahat ng English “I am” ay ser o estar.','Tener expresses possession and appears in age and some state expressions: tengo veinte años, tengo hambre. Its present forms include tengo, tienes, tiene.','Age: tengo + number + años. Possession: tengo + thing.'],
 [/\b(?:está|están)\b/i,'estar + state or location','Está para sa él/ella/usted o singular na bagay; están para sa ellos/ellas/ustedes o plural. Gamitin ang buong sentence para malaman kung state o location. Hindi automatic na “temporary” ang lahat ng estar.','Está and están are present forms of estar. Match singular or plural and use context to distinguish a state from a location.','One: está. More than one: están.'],
 [/\b(?:es|son)\b/i,'ser + description, identity, or time','Es para sa singular; son para sa plural. Sa la casa es grande, description ang kasunod. Sa son las tres, oras ang sinasabi. Ang location ng event ay puwede ring ser: la clase es aquí.','Es and son are present forms of ser. Ser is used for descriptions, identity, time, and the location of events, among other uses.','Es for one, son for several; for time, es la una / son las dos.'],
 [/\b(?:fui|fuiste|fue|fuimos|fueron)\b/i,'shared preterite forms: ser / ir','Pareho ang preterite forms ng ser at ir: fui, fuiste, fue, fuimos, fueron. Sa fui al mercado, destination kaya ir. Sa fui estudiante, identity kaya ser. Context ang pipili, hindi spelling lang.','Ser and ir share these preterite forms. A destination in fui al mercado points to ir; an identity in fui estudiante points to ser.','Fui can mean I went or I was. Read the complement.'],
 [/\b(?:hablo|hablas|habla|hablamos|hablan|estudio|estudias|estudia|trabajo|trabajas|trabaja)\b/i,'regular present -ar: stem + ending','Sa regular present -ar verb, tanggalin ang -ar at idagdag ang person ending. Hablar → habl- + o = hablo, + as = hablas, + a = habla. Tandaan: may words na maaari ring noun o command, kaya context pa rin.','Regular present -ar verbs use a stem plus person ending: hablar → hablo, hablas, habla. A matching spelling alone does not decide whether a word is a noun, statement, or command.','Keep habl-, change the ending; do not attach -o to the full hablar.'],
 [/\b(?:como|comes|comemos|vivo|vives|vive|vivimos|leo|lees|lee|veo|ves|ve)\b/i,'present -er / -ir and irregular yo forms','Comer → como, comes, come; vivir → vivo, vives, vive. Nosotros differs: comemos pero vivimos. May irregular yo forms tulad ng veo; huwag gawing regular ang lahat. Ang como ay maaari ring “as,” kaya basahin sa context.','Present -er and -ir verbs share several endings but differ in nosotros: comemos / vivimos. Some yo forms are irregular, such as veo. Como may also be a conjunction meaning as.','Nosotros: -emos for comer, -imos for vivir.'],
 [/\b(?:sé|sabe|sabes|entiendo|entiende|entiendes)\b/i,'saber / entender + what is known or understood','Sé = I know; entiendo = I understand. Irregular ang sé at may accent. Sa entender → entiendo, nagiging ie ang stressed e. No sé at no entiendo ay magkaibang meaning.','Sé is the irregular present yo form of saber. Entiendo is a stem-changing present form of entender. Knowing and understanding are different ideas.','Know: sé. Understand: entiendo. Keep the accent in sé.'],
 [/^(?:hola|buenos días|buenas tardes|buenas noches|mucho gusto|hasta luego|hasta mañana|perdón|¿y tú|para aquí|a la derecha|a la izquierda|todo recto)[.!?¿\s]*$/i,'a useful fixed expression','Fixed expression ito: aralin bilang buong chunk kasama ang meaning at situation. Walang conjugated verb na kailangang baguhin sa mismong expression na ito. Halimbawa, buenos días ay greeting, hindi verb sentence.','This is a fixed expression or phrase fragment rather than a clause requiring a conjugated verb. Learn the complete chunk and when to use it.','Recall the situation first, then say the whole expression aloud.'],
 [/\bme llamo\b/i,'me + llamo + name','Me llamo = ang pangalan ko. Ang llamar ay “to call”; llamo ang yo form, at me ang tumutukoy sa sarili. Kaya “I call myself” ang literal na pattern.','Me llamo introduces your own name: me marks yourself, and llamo is the present yo form of llamar.','Keep me with llamo when introducing yourself.'],
 [/\b(?:puedo|puedes|puede|podemos|pueden|podría|podrías)\b/i,'poder + infinitive','Ang poder ang binabago ayon sa tao at tense: puedo para sa yo, puedes para sa tú, puede para sa usted. Kapag may kasunod na action verb, infinitive ito: puedo ayudar, hindi puedo ayudo.','Conjugate poder for the person and tense; a following action verb stays in the infinitive. Puedo ayudar means I can help.','Link the two verbs when recalling the phrase: puedo + ayudar.'],
 [/\b(?:voy|vas|va|vamos|van) a\b/i,'ir + a + infinitive or destination','Voy ang yo form ng ir. Sa voy a revisar, a + infinitive ang plano. Sa voy a la estación, lugar ang kasunod kaya pupunta ka roon. Tingnan ang kasunod ng a bago mag-translate.','Ir a + infinitive expresses an intended action; ir a + destination describes going somewhere.','Distinguish voy a revisar from voy a la estación.'],
 [/\b(?:tengo|tienes|tiene|tenemos|tienen) que\b/i,'tener + que + infinitive','Tener que + infinitive ang “have to.” Ang unang verb lang ang iko-conjugate: tengo que revisar para sa ako; tiene que revisar para sa usted. Huwag alisin ang que.','Tener que + infinitive expresses an obligation. Change tener for the subject and keep the following verb in its base form.','Remember the whole bridge: tengo QUE hacer.'],
 [/\b(?:me|te|le|nos|les) (?:gusta|gustan)\b/i,'recipient + gusta/gustan + thing liked','Sa gustar, ang bagay na gusto ang nagdidikta ng gusta o gustan. Me gusta el café pero me gustan los libros. Ang me/te/le ang nagsasabi kung sino ang may gusto.','Gustar agrees with the thing liked, not with the person who likes it. Use gusta with an infinitive or singular thing, and gustan with plural things.','One thing: gusta. Several things: gustan.'],
 [/\bquisiera\b/i,'quisiera + noun or infinitive','Quisiera ay form ng querer na madalas gamitin sa magalang na request: quisiera un café. Maaari itong tumukoy sa yo o él/ella/usted; context ang clue. Hindi ito simpleng present-tense ending.','Quisiera is an imperfect-subjunctive form of querer, often used for a polite wish or request. The subject depends on context.','Learn quisiera as a polite request chunk before changing its person.'],
 [/\bhay\b/i,'hay + what exists','Hay = mayroon o may. Hindi ito nagiging plural kapag marami: hay una mesa at hay dos mesas. Iba ito sa está/están na nagsasabi kung nasaan ang isang kilalang bagay.','Existential hay does not change for singular or plural: hay una mesa / hay dos mesas. Use está or están to locate a known thing.','Hay introduces; está locates.'],
 [/\b(?:soy|eres|somos)\b/i,'ser + identity, origin, or description','Soy ang yo form ng ser; eres para sa tú, somos para sa nosotros. Gamit ito sa identity at origin, tulad ng soy estudiante o soy de México. Hindi sapat ang “permanent vs temporary” na shortcut.','Ser expresses identity and origin, among other uses. Soy, eres, and somos are irregular present forms.','Pair the person and form: yo soy, tú eres, nosotros somos.'],
 [/\b(?:estoy|estás|estamos)\b/i,'estar + state, location, or -ndo form','Estoy para sa yo, estás para sa tú, estamos para sa nosotros. Sa estoy bien, state ang kasunod; sa estoy en casa, location; sa estoy aprendiendo, action in progress.','Estar can describe a state or location, and combines with a gerund for an action in progress.','Remember estoy + state/place, and estoy + -ndo for an ongoing action.'],
 [/\b(?:quiero|quieres|quiere|queremos|quieren)\b/i,'querer + action / querer que + another clause','Quiero + infinitive kapag ako rin ang gagawa: quiero hablar. Kapag ibang subject, madalas querer que + subjunctive: quiero que hables. Huwag basta palitan lahat ng second verbs ng infinitive.','Querer + infinitive usually shares the subject. Querer que + a new clause typically uses subjunctive for the desired action.','Same doer: quiero hablar. New doer: quiero que hables.'],
 [/\b(?:necesito|necesita|necesitas|necesitamos)\b/i,'necesitar + noun or infinitive','Necesitar ay regular -ar verb: necesit- + o = necesito; + as = necesitas; + a = necesita. Kapag action ang kailangan, infinitive ang kasunod: necesito confirmar.','Regular present necesitar uses the stem necesit- and person endings: necesito, necesitas, necesita. A following action uses the infinitive.','Keep the stem necesit- and change only the person ending.'],
 [/\b(?:he|has|ha|hemos|han) (?:\p{L}+ado|\p{L}+ido|hecho|dicho|visto|vuelto|puesto|abierto|escrito)\b/iu,'haber + past participle','Sa present perfect, haber ang nagbabago ayon sa tao: he, has, ha, hemos, han. Ang participle ay hindi nagbabago sa gender pagkatapos ng haber: he hablado, hemos hablado.','The present perfect combines a form of haber with a past participle. After haber, the participle does not agree in gender or number.','Change haber, keep the participle.'],
 [/\b(?:por favor|gracias|de nada)\b/i,'courtesy expressions','Por favor = pakiusap/please; gracias = salamat; de nada = walang anuman. Fixed expressions ang mga ito; hindi mo iko-conjugate ang mismong phrase. Kung may verb sa ibang bahagi, doon nagbabago ang person o tense.','Courtesy expressions such as por favor, gracias, and de nada are fixed phrases; they do not themselves conjugate. Any surrounding verb follows its own pattern.','Request → por favor; thanks → gracias; reply → de nada.'],
 [/\b(?:cuando|mientras|después|antes|ayer)\b/i,'time clues + the event','Hanapin ang time clue: ayer = kahapon, mientras = habang, después = pagkatapos. Clue lang ito, hindi automatic na isang tense lagi. Ikumpara ang completed event at background sa context.','Time expressions help organize events, but do not mechanically choose the tense. Identify whether the speaker presents an event, background, habit, or future situation.','Retell in order: first, next, finally; then check the tense of each event.']
];
const boundary='(?:(?<![\\p{L}\\p{M}])(?=[\\p{L}\\p{M}])|(?<=[\\p{L}\\p{M}])(?![\\p{L}\\p{M}]))';
const matchingRules=rules.map(([pattern,...notes])=>[new RegExp(pattern.source.replaceAll('\\b',boundary),pattern.flags.includes('u')?pattern.flags:pattern.flags+'u'),...notes]);
const lexicon={no:'not / no',y:'and',pero:'but',porque:'because',para:'for / in order to',con:'with',sin:'without',de:'of / from',en:'in / on / at',antes:'before',después:'after',aquí:'here',allí:'there',hoy:'today',mañana:'tomorrow / morning',ayer:'yesterday',ya:'already / now',todavía:'still / yet',también:'also / too',usted:'you (formal singular)',tú:'you (informal singular)',yo:'I',nosotros:'we',ustedes:'you (plural)',mi:'my',su:'his / her / your / their',que:'that / linking word',qué:'what / which',cómo:'how',cuándo:'when',dónde:'where',si:'if / whether',sí:'yes'};
const tokens=s=>String(s).toLocaleLowerCase('es').match(/[\p{L}\p{M}]+/gu)||[];
const formIndex=new Map();
for(const verb of verbs)for(const tense of Object.keys(tenseInfo)){
 const forms=getForms(verb,tense);if(!forms)continue;
 forms.forEach((form,person)=>{const key=tokens(form).join(' ');const entries=formIndex.get(key)||[];entries.push({infinitive:verb.infinitive,tense,person,form});formIndex.set(key,entries);});
}
export function verbMatches(spanish){
 const words=tokens(spanish),matches=[];
 for(let i=0;i<words.length;i++)for(const length of [2,1]){
  const key=words.slice(i,i+length).join(' ');
  for(const match of formIndex.get(key)||[])if(!matches.some(m=>m.infinitive===match.infinitive&&m.tense===match.tense&&m.person===match.person&&m.form===match.form))matches.push(match);
 }
 return matches;
}
export function supportFor(spanish,english,tip=''){
 const selected=matchingRules.find(([pattern])=>pattern.test(spanish));
 const words=[...new Set(tokens(spanish))].filter(w=>lexicon[w]).map(w=>[w,lexicon[w]]);
 return {spanish,english,pattern:selected?.[1]||'Meaning → who → action or description → details',
 taglish:selected?.[2]||'Unahin ang buong meaning, hindi word-for-word. Hanapin kung sino ang pinag-uusapan, ano ang action o description, at anong detalye ang idinadagdag. Ang maliit na words sa ibaba ang nag-uugnay ng ideas. Kapag may verb, piliin ang person at tense; kapag fixed expression, aralin bilang isang chunk.',
 explanation:selected?.[3]||'Start with the complete meaning, identify who or what is being discussed, and separate the action or description from its details. Use the linking-word meanings below. Conjugate verbs for the intended person and tense; fixed expressions are learned as chunks.',
 proTip:tip||selected?.[4]||'Read the Spanish aloud, then check its full English meaning. Change one detail at a time; preserve the verb’s person and the intended tone.',
 memory:selected?.[4]||'Cover the Spanish, use the English as your cue, and rebuild the expression in small chunks. Reveal it, compare, and try once more.',words,matches:verbMatches(spanish)};
}
