import test from 'node:test';
import assert from 'node:assert/strict';
import {localDay,discoveryFor,discoveryEntries,shouldShowDiscovery} from '../src/daily-discovery.js';
import {octoberGrammar,octoberCalls,octoberStories} from '../src/october-lessons.js';
import {normalize} from '../src/practice-state.js';
test('daily discovery is stable within a local day and rotates at midnight',()=>{const early=new Date(2026,9,3,0,1),late=new Date(2026,9,3,23,59),next=new Date(2026,9,4,0,0);assert.equal(localDay(early),'2026-10-03');assert.equal(discoveryFor(early).id,discoveryFor(late).id);assert.notEqual(discoveryFor(late).id,discoveryFor(next).id);assert.equal(shouldShowDiscovery('2026-10-03',late),false);assert.equal(shouldShowDiscovery('2026-10-03',next),true);assert.equal(shouldShowDiscovery('broken',early),true);});
test('daily entries offer translations and memory-ready models for both words and verbs',()=>{assert.equal(new Set(discoveryEntries.map(e=>e.id)).size,discoveryEntries.length);assert.ok(discoveryEntries.some(e=>e.kind==='Word'));assert.ok(discoveryEntries.some(e=>e.kind==='Verb'));for(const e of discoveryEntries){for(const k of ['term','meaning','example','translation','explanation','taglish','tip'])assert.ok(e[k]);if(e.kind==='Verb')assert.equal(e.forms.length,6);}});
test('new language practice distinguishes tense, accent and agreement',()=>{assert.equal(octoberGrammar.length,4);for(const x of octoberGrammar){assert.equal(x.table.length,6);assert.equal(x.tasks.length,3);assert.equal(x.examples.length,3);}for(const [a,b] of [['Hemos revisado las notas.','Hemos revisados las notas.'],['Sé que el sistema funciona.','Sé que el sistema funcione.'],['Ella hizo una prueba.','Ella hice una prueba.'],['Podría confirmar el importe.','Podria confirmar el importe.']])assert.notEqual(normalize(a),normalize(b));});
test('new calls and stories retain bilingual feedback and comprehension',()=>{assert.equal(octoberCalls.length,2);for(const s of octoberCalls){assert.equal(s.turns.length,6);for(const t of s.turns){assert.ok(t.customer&&t.translation&&t.model&&t.english&&t.why&&t.taglish);assert.equal(t.bad.length,3);}}assert.equal(octoberStories.length,3);for(const r of octoberStories){assert.ok(r.tip&&r.proTip&&r.taglish);assert.ok(r.lines.length>=8);for(const line of r.lines)assert.equal(line.filter(Boolean).length,2);for(const q of r.questions)assert.ok(q[1][q[2]]&&q[3]);}});
